### ISSUE TITLE
Request: Include Whitelist for Smart Referer extension

### ISSUE THREAD

**Issue by BreadYogurt** [iamadamdev/bypass-paywalls-firefox#10]
I use this extension alongside [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/), which spoofs the referer of cross-site headers. But, this tends to override Bypass Paywalls, since they both spoof the referer. The result is that the paywall tends to be shown because instead of the referal header being for Google or Facebook, it is for the site being visited.

Fortunately, Smart Referer has whitelisting capabilities, and even allows downloading whitelists from online sources. [I made a whitelist to take advantage of this functionality](https://pastebin.com/aveee9DE), but since it relies on a specific list of sites, whenever Bypass Paywalls supports a new site, I'd have to add that site to the whitelist if I wish to not worry about such things in the future.

So, I would really appreciate it if there was an official Smart Referer whitelist for this project. That way, those that use both extensions can add the whitelist to Smart Referer, and as new sites are supported, they can be added to the whitelist. It should be possible to simply host the whitelist within the Github repo.

**Comment by iamadamdev** [comment]
If usage of that extension becomes more widespread and this becomes a larger issue I would consider it.
