### ISSUE TITLE
Firefox/Android: Selections of sites not "sticking"

### ISSUE THREAD

**Issue by stareyedwonder** [iamadamdev/bypass-paywalls-firefox#101]
Hi!

This is a great add-on; I love it. Thanks for putting in the work.

Using 1.4.6 of the add-on (and also previous versions) with Firefox on Android (in this case 64.0.1 on Oreo; previous versions, too)  when I go to select the sites to have their cookies cleared and referers set, my selections never "stick". I could, for example, de-select Barron's, leave the selection area of the add on, and then return, only to find my de-selection un-de-selected. There's no way to save de-selections/selections. This is a bit of a pain because I need to entirely disable the add-on whenever I wish to access the sites to which I subscribe. Any way to fix this?

Thanks!!

**Comment by iamadamdev** [comment]
Are you unchecking the site and then scrolling all the way down to hit 'Save'?
I just tried unchecking sites on a Samsung Galaxy S9, running Android 8.0 Oreo, on the latest version of mobile Firefox, running my extension v1.4.6 and it saved my unchecked selections just fine. (Even closed out the Firefox app completely and re-opened, my saved sites still there).

**Comment by stareyedwonder** [comment]
Ahh! Pretty tricky! ;-}

I'm still glad I asked. I looked like crazy for the save button which I was expecting to see since I see it on the windows version. On the android version, if one scrolls to the bottom, the scrolling stops at the last website on the list --- but that DOES NOT show you the "save" button, which remains hidden. You have to scroll down a second time before you see it. As a result, unless you scroll down a second time, you're left with the impression that there's no save button.

Thanks for answering this.
