### ISSUE TITLE
Request for a website to bypass

### ISSUE THREAD

**Issue by Divinejf** [iamadamdev/bypass-paywalls-firefox#102]
Could you get your bypass paywall thing to bypass ACS's Chemical and Engineering News website. Its website is https://cen.acs.org/index.html. It only lets you read 5 articles a month without a paid subscription. I tried opening articles in Chrome's InCognito Mode, and it thankfully does not notice that I've already read other articles, so the bypass paywall thing will actually work for this website. Thanks for all your hard work and time!

**Comment by iamadamdev** [comment]
Added in https://github.com/iamadamdev/bypass-paywalls-firefox/releases/download/v1.4.7/bypass_paywalls-1.4.7-an+fx.xpi
