### ISSUE TITLE
Central Illinois Newspapers

### ISSUE THREAD

**Issue by kstev99** [iamadamdev/bypass-paywalls-firefox#104]
Thank you for the BEST paywall extension and great support.  I have a couple of Central IL newspapers I would like you to add in the future if it is possible.

Mattoon Journal-Gazette (10 article limit)
https://jg-tc.com/

Decatur Herald-Review
https://herald-review.com/    (10 or 15 article limit)

**Comment by iamadamdev** [comment]
I prefer avoiding adding all the countries's local newspapers.
I would suggest using https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/
and delete the cookies on those sites when you hit the limit.
