### ISSUE TITLE
Add Github URL to Options page

### ISSUE THREAD

**Issue by Nicholas-Steel** [iamadamdev/bypass-paywalls-firefox#105]
Add a clickable URL to this Github somewhere in the add-on options (Firefox).

**Comment by iamadamdev** [comment]
Added.

**Comment by iamadamdev** [comment]
It's in 1.4.7 now which was released a while ago.

**Comment by Nicholas-Steel** [comment]
Ah I see it now, I actually meant for the URL to be visible when viewing the Options for it via the about:addons page.
