### ISSUE TITLE
[Question] Why access to all websites?

### ISSUE THREAD

**Issue by xmppwasabi** [iamadamdev/bypass-paywalls-firefox#106]
I have a question, why the add-on requires access to all sites while it works only on a limited list of websites? Similar add-ons only require such access for the websites they work with, I think it is a safer approach (but I suppose more time consuming for the developer who has to add new ones each time). I am just curious.

**Comment by iamadamdev** [comment]
Exactly for the reason you listed. Initially I had manually added access for each site, but it become too time consuming.
If you want to go ahead and manually add permissions for each site please go ahead and submit a PR.

thanks
