### ISSUE TITLE
Can you add valor.com.br to the list? 

### ISSUE THREAD

**Issue by esteves023** [iamadamdev/bypass-paywalls-firefox#11]
First of all, thank you.

Second, I thought FT was the hardest website to bypass out there, but valor.com.br (brazilian financial webpage) is definetly the hardest. I've tried everything. Disabling javascript won't work either.

Maybe your extension is the answer? I still think there's no way though, their paywall is somewhat different, maybe a server side paywall, not sure. 

If you by any chance have the time and curiosity to try and add it, I'd be very grateful. Notice that their webpage have some free articles and some locked ones (with a key sign beside the headline).

**Comment by iamadamdev** [comment]
Won't work for the locked articles on that site.
