### ISSUE TITLE
WSJ.com no longer working

### ISSUE THREAD

**Issue by rub3x** [iamadamdev/bypass-paywalls-firefox#115]
WSJ appears to no longer work with this plugin.  It looks like they stopped showing content for traffic originating with a referring URL of Facebook.com.  Not sure what this plugin used to bypass the paywalls but traffic originating from Facebook definitely used to grant access to the content very recently.

**Comment by 4549** [comment]
Maybe you can try to turn off **uBlock Origin**. When I turn off it, I can read WSJ articles.

**Comment by rub3x** [comment]
Yes, that did it.  Thanks.

**Comment by ssathya** [comment]
No luck; tried turning off uBlock Origin then also tried turning off Ghostery's did not help.

**Comment by rub3x** [comment]
Try using a privacy/incognito tab and make sure you're allowing cookies from WSJ.

**Comment by compuguy** [comment]
@rub3x The purpose of the addon is to automate that process. Disabling uBlock origin doesn't seem to help.

**Comment by ssathya** [comment]
> 
> 
> Try using a privacy/incognito tab and make sure you're allowing cookies from WSJ.

Did not help!
![2019-01-30 16_38_46-window](https://user-images.githubusercontent.com/1380944/52014486-a6545e80-24ad-11e9-8f89-543d9e357352.png)

**Comment by johnda3** [comment]
Still not working. I guess WSJ IT reads this. Consider it a compliment.

**Comment by iamadamdev** [comment]
I think you are the only one it is not working for. You must have messed up your settings.
