### ISSUE TITLE
WSJ Still Not Working

### ISSUE THREAD

**Issue by ChopperDog** [iamadamdev/bypass-paywalls-firefox#118]
I have tried all of the solutions from the discussion 3 days ago and none work. I have updated to the latest version, paused uBlock, tried a different browser, cleared all history and cookies, allowed cookies from the site. Is anyone else having this issue?

**Comment by rourpab** [comment]
Yeah, not working

**Comment by compuguy** [comment]
This was discussed as well in #115, which is closed for some reason.

**Comment by iamadamdev** [comment]
WSJ changed their algo, even going to an article from Google Search results in Private mode or Incognito mode doesn't work.
Not much I can do here.

**Comment by cynopt** [comment]
It looks like you can get around the paywall by replacing the end of the URL (starting at the ?) with "?mod=rsswn".

**Comment by VernonStow** [comment]
> 
> 
> It looks like you can get around the paywall by replacing the end of the URL (starting at the ?) with "?mod=rsswn".

Does not work for me with Firefox 65.0, even in a private tab.

**Comment by iamadamdev** [comment]
WSJ bypass fixed in v1.4.9
