### ISSUE TITLE
It looks like you can get around the paywall by replacing the end of the URL (starting at the ?) with "?mod=rsswn".

### ISSUE THREAD

**Issue by ChopperDog** [iamadamdev/bypass-paywalls-firefox#120]
It looks like you can get around the paywall by replacing the end of the URL (starting at the ?) with "?mod=rsswn".

_Originally posted by @cynopt in https://github.com/iamadamdev/bypass-paywalls-firefox/issues/118#issuecomment-461109831_

**Comment by ChopperDog** [comment]
This works for me...
https://www.wsj.com/articles/inspection-of-vale-dam-in-brazil-issued-warning-before-collapse-11549485427?mod=hp_lead_pos5
Becomes
https://www.wsj.com/articles/inspection-of-vale-dam-in-brazil-issued-warning-before-collapse-11549485427?mod=rsswn

Not all url end with something similar to "?mod=hp_lead_pos5" but add "?mod=rsswn" to the end (no quotes) and some work.

**Comment by chuckufarlie** [comment]
This works perfectly, thanks.

**Comment by iamadamdev** [comment]
WSJ bypass fixed in v1.4.9
