### ISSUE TITLE
Hbr.org

### ISSUE THREAD

**Issue by vipuldsharma** [iamadamdev/bypass-paywalls-firefox#123]
Sir ,I have installed both your bypass paywalls and ublock origin,but it keeps showing the remaining articles count in the bottom window and because of which I am not able to read more than three articles,Please help me sir.I am using firefox 65.0

**Comment by vipuldsharma** [comment]
Only able to read 3 articles, please admin, kindly resolve my issue

**Comment by iamadamdev** [comment]
Fixed in v1.4.9
