### ISSUE TITLE
New Constructs

### ISSUE THREAD

**Issue by jlynch089** [iamadamdev/bypass-paywalls-firefox#124]
Hi.. I was hoping there would be a way to bypass the New Constructs paywalls. New Constructs is a premium website for research in stocks, ETFs, etc... an article is linked below:

https://www.newconstructs.com/avoid-value-traps-with-this-deep-value-etf/?utm_source=newsletter&utm_medium=email&utm_campaign=20190206LongIdeaDPV&inf_contact_key=5303883bc8f6f62f89237a267129211fcc0558ed5d4c28cbfab114022b1ec50d

Let me know if there is something that can be done. If not, I still appreciate all your hard work with the paywall chrome extension!

Cheers,

Josh

**Comment by iamadamdev** [comment]
Unfortunately that is a hard paywall so it cannot be bypassed.
