### ISSUE TITLE
New York Magazine

### ISSUE THREAD

**Issue by mb389** [iamadamdev/bypass-paywalls-firefox#129]
http://nymag.com

thanks for this extension!

**Comment by iamadamdev** [comment]
Where are you seeing a payall? Do you have uBlock Origin installed?
I loaded 10+ articles just fine.

**Comment by mb389** [comment]
Hey, they may have only rolled it out to some fraction of users, but this is what I see. Same message with uBlock enabled or disabled.
<img width="1181" alt="screen shot 2019-02-18 at 4 34 18 pm" src="https://user-images.githubusercontent.com/12397314/52977489-735e0600-339b-11e9-8692-03c9538df75f.png">

**Comment by iamadamdev** [comment]
Added to v1.5.0
