### ISSUE TITLE
The Australian

### ISSUE THREAD

**Issue by Jarijari7** [iamadamdev/bypass-paywalls-firefox#132]
Hi Adam, fine job as usual. Any chance of adding The Australian https://www.theaustralian.com.au/ to the list. Thanks.

**Comment by bossanova808** [comment]
A quick look at this suggests:

Remove class `lightclass-open` from `<html class="lightcase-open">` at the top of document

Remove divs with these classes from the document: 
`lightcase-*` 
(i.e. `lightcase-overlay`,`lightcase-loading`,`lightcase-case`,`lightcase-nav`)
`subscribe-popover`

...should do it (at least when it pops up the subscribe pop-over with the 'No Thanks' option - it might go more hardcore later but there's only so much murdoch propaganda I can bother looking at!)

**Comment by bossanova808** [comment]
(@iamadamdev I have no idea how to work on Firefox addons so it would take me a few hours to do that stuff above and you can probably do it in a few seconds...hence no PR!)

**Comment by bossanova808** [comment]
Gist of a userscript to do this here - https://gist.github.com/bossanova808/515dddeb8e7f459457b5a94479ded876

...ther's a bit of a flash as the overlay is loaded then removed...but works.

**Comment by bossanova808** [comment]
(and if you use stylish you can simplify that script and stop even the initial flash occuring - see gist!)

**Comment by gregbruhsyd** [comment]
Hi Adam, great extension ! Could you please add the Australian and the Australian Financial Review (afr.com). cheers

**Comment by iamadamdev** [comment]
@bossanova808 some articles are still showing a paywall even after removing cookies and using your gist, e.g., https://www.theaustralian.com.au/business/media/broadcast/qa-panel-clashes-over-pill-testing-at-music-festivals/news-story/27263bccb958c18fcc45169cdd1ff96d

@gregbruhsyd afr.com was already added some time ago...

**Comment by bossanova808** [comment]
@iamadamdev That loads just fine here.  Are you using the JS part of just the css rules?  Without the JS part, the paywall should be cleared but you won't be able to scroll IIRC

But it might be something else that kicks in if you read more articles on there??  I haven't hit it yet, if so

**Comment by bossanova808** [comment]
(I updated the simpler method in the gist in case it wasn't clear the JS bit still has to happen after the window's load event)

**Comment by bossanova808** [comment]
@iamadamdev I do notice if I go to another tab (during the annoyingly long wait for a page on The Australian to load...) - the js doesn't seem to run and I can't scroll without a reload...is that what you mean?

**Comment by gregbruhsyd** [comment]
Hi,

Actually I'm using your Chrome paywall feature. I'm not that much of a techie, which makes me unable to answer your questions (what is js ?).

I just gave it a go yesterday, opening The Australian and AFR.com articles in a incognito tab, which worked, hence my suggestion to add them.

But later, I tried your extension with the Sydney Morning Herald, and it wasn't working: I used up my five free articles per month and after that, nothing was accessible anymore.

Maybe I did something wrong ? I followed every step indicated on your Github (although I don't use UBlock).

________________________________
De : Jeremy Daalder <notifications@github.com>
Envoyé : mardi 19 février 2019 04:53
À : iamadamdev/bypass-paywalls-firefox
Cc : gregbruhsyd; Mention
Objet : Re: [iamadamdev/bypass-paywalls-firefox] The Australian (#132)


@iamadamdev<https://github.com/iamadamdev> I do notice if I go to another tab (during the annoyingly long wait for a page on The Australian to load...) - the js doesn't seem to run and I can't scroll without a reload...is that what you mean?

**Comment by iamadamdev** [comment]
Australian sites seem to try to prevent bypassing the paywall (and change their algorithm frequently) so this extension isn't reliable in bypassing them.

**Comment by Jarijari7** [comment]
Greg, I've been able to access SMH, Age etc using esc key as the article loads. AFR working fine on the extension.

**Comment by iamadamdev** [comment]
Added in the latest version v1.5.2
