### ISSUE TITLE
WaPo not working in EU

### ISSUE THREAD

**Issue by lizadoolittle** [iamadamdev/bypass-paywalls-firefox#135]
Running version 1.4.9. Washington Post blocked by paywall. I have installed Ublock Origin and have tried disabling and refreshing the page.

**Comment by iamadamdev** [comment]
Try v1.5.0

**Comment by s1shed** [comment]
With v1.5.1, in the EU I get the EU GDPR prompt for every article when this addon is active for WaPo. 

At https://github.com/iamadamdev/bypass-paywalls-chrome/issues/22#issuecomment-462065617_  @mikadocat stated that https://github.com/r4vi/block-the-eu-cookie-shit-list worked for him. It doesn't work for me.

What *does* work for me is adding `||pwapi.washingtonpost.com^` as a filter to µBlock and unselecting WaPo in this extension. With this configuration I see neither the EU prompts nor the paywalls.

**Comment by s1shed** [comment]
Now that they've updated their site the rule I pasted above no longer works. Bugger.

Now I just have to approve each EU cookie prompt until I can find a way to ignore them. Anyhow, thank you for this very useful addon!

**Comment by kristofferR** [comment]
> Now I just have to approve each EU cookie prompt until I can find a way to ignore them. Anyhow, thank you for this very useful addon!

I've submitted a PR (https://github.com/iamadamdev/bypass-paywalls-chrome/pull/233) for a fix for this, that'll solve that issue. It's for the Chrome version, but as it's really basic JS it should be a breeze to port over to the FX version :)
