### ISSUE TITLE
fd.nl not working

### ISSUE THREAD

**Issue by qazwsxedcgit** [iamadamdev/bypass-paywalls-firefox#138]
Using version 1.5.1 of the addon with version 60.5.0esr (64-bit) of Firefox it is not possible to bypass the paywall at fd.nl. Clicking on any headline results in presentation by the site of a modal "accept cookies" dialog, and then a registration or login prompt.

(Good job on fixing ft.com so fast, btw!)

**Comment by iamadamdev** [comment]
I think they are hardwalling everything now?
