### ISSUE TITLE
Request Bypass https://www.dagbladet.no/

### ISSUE THREAD

**Issue by TatsuyaMiyuki** [iamadamdev/bypass-paywalls-firefox#139]
Sir, can you bypass https://www.dagbladet.no/nyheter/forteller-fra-innsiden-om-en-av-verdens-farligste-menn---kompisen-min-ble-propagandasjef-i-is/68576721 ...? Thanks You

**Comment by iamadamdev** [comment]
Small local papers are not being added anymore.
