### ISSUE TITLE
TheGlobeandMail.com - not working

### ISSUE THREAD

**Issue by stareyedwonder** [iamadamdev/bypass-paywalls-firefox#14]
Thanks for adding this just recently!! Unfortunately, it seems the add-on still can't get past the paywall at TheGlobeandMail.com. This is with cookies cleared (all cookies are cleared at every browser shutdown on my machine) and with uBlock Origin either disabled or enabled. Any thoughts? Thanks again!!

**Comment by iamadamdev** [comment]
Which article isn't loading for you?
OS and FF version?
I'm on Firefox 59.0.2 on Windows 10 and it works fine.

**Comment by stareyedwonder** [comment]
It's happening on:

60.0.2 Android 8.0.0
60.0.2 Windows 7-64
52.8.1 Windows XP-32

As an example:

https://www.theglobeandmail.com/business/streetwise/article-former-competition-commissioner-john-pecman-joining-law-firm-fasken/

Thanks for checking!

**Comment by stareyedwonder** [comment]
I should add that if I disable all other add-ons save for the present, the behavior persists.

**Comment by iamadamdev** [comment]
I see. That is expected, article doesn't load for me either, those are premium articles.

**Comment by stareyedwonder** [comment]
Is there no way around this using the techniques you're using? When I click on those articles, I notice the article appears, but then, a moment afterward, the article is "collapsed", and an overlay appears. I can easily stop this behavior by disabling cookies; when I do that, I can read the article. Of course, having to disable cookies just so I can read that site is inconvenient...

**Comment by iamadamdev** [comment]
I tried various methods of removing and blocking the cookies in an extension but the paywall still appeared. So far only manually disabling cookies in Firefox options allowed me to read the article. Did you use any cookie blocking extensions? if so which one worked?
