### ISSUE TITLE
remove cookie warnings

### ISSUE THREAD

**Issue by ari1010** [iamadamdev/bypass-paywalls-firefox#141]
If most site cookie warning operate the same way, it would be a nice feature to remove that warning as part of bypass-paywalls-firefox

**Comment by iamadamdev** [comment]
Can you submit a PR for the site you are talking about?

**Comment by ari1010** [comment]
I wasn't suggesting this for just one site. I thought the cookie warning might operate in a similar way for lots of sites and could be dealt with generally.

But anyway, the one that was really bugging me was.....

https://www.irishtimes.com/
