### ISSUE TITLE
Some German newspapers: Spiegel, FAZ, BILD et al. – support possible?

### ISSUE THREAD

**Issue by JayBrown** [iamadamdev/bypass-paywalls-firefox#143]
It was already mentioned [**here**](https://github.com/iamadamdev/bypass-paywalls-firefox/issues/2) that *Die Zeit* and *Sueddeutsche* won't work. (Unless something has changed in the meantime.) But maybe the following will?

**Spiegel Online**: http://www.spiegel.de/
Paywall article (Spiegel+): http://www.spiegel.de/plus/kim-jong-un-und-donald-trump-vor-atomgipfel-was-haben-sie-zu-bieten-a-00000000-0002-0001-0000-000162534118

**FAZ**: https://www.faz.net
Paywall article (F+): https://www.faz.net/aktuell/wirtschaft/diginomics/kommentar-zur-onlinewelt-der-internet-irrtum-16055491.html

**Bild**: https://www.bild.de/
Paywall article (BildPlus): https://www.bild.de/bild-plus/reise/traumreisen/traumreise/die-guenstigsten-und-beliebtesten-pauschalreiseziele-fuer-den-sommer-2019-60300220,view=conversionToLogin.bild.html

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
