### ISSUE TITLE
Firefox prevented this site from asking you to install on your computer

### ISSUE THREAD

**Issue by ogirginc** [iamadamdev/bypass-paywalls-firefox#152]
I had to re-install but FF prevented me. If same happens to you, follow these steps:
1) Go to `about:preferences#privacy`
2) Uncheck "Warn you when websites try to install add-ons"
3) Go to [readme](https://github.com/iamadamdev/bypass-paywalls-firefox#bypass-paywalls-for-firefox) and install the add-on.
4) Go back to privacy settings and check "Warn you when websites try to install add-ons".

**Comment by iamadamdev** [comment]
I have that checked and it still installs fine. Just click "Allow" when it says "Firefox prevented this site from asking you to install software on your computer."

**Comment by ogirginc** [comment]
> Just click "Allow"
For some reason it didn't work for me. :)
