### ISSUE TITLE
News Corp Sites

### ISSUE THREAD

**Issue by Venom1995** [iamadamdev/bypass-paywalls-firefox#159]
Do you think you could add some of the other News Corp sites? Preferably these ones:

https://www.dailytelegraph.com.au/
https://www.heraldsun.com.au/
https://www.couriermail.com.au/?nk=da9b8d5fdd344b4a63d3782c0987afd2-1532303437
https://www.adelaidenow.com.au/
https://www.themercury.com.au/
https://www.ntnews.com.au/?nk=03ebcdd712d1d537e8596a56eabb2161-1552267252

**Comment by iamadamdev** [comment]
None of the Australian news.com.au sites work
https://github.com/iamadamdev/bypass-paywalls-firefox/blob/master/README.md#new-site-requests
