### ISSUE TITLE
smh.com.au is not working

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-firefox#161]
While you can see a few free articles, once the free limit has been reached, it is showing this page: https://imgur.com/a/zrMp5TH

All this is happening even though Bypass Paywalls is enabled and all sites are enabled.

Please fix ASAP.

Thanks.

PS: Story Link: https://www.smh.com.au/national/nsw/northern-beaches-it-guru-allegedly-made-300-000-from-stolen-netflix-logins-20190313-p513u6.html

**Comment by iamadamdev** [comment]
I loaded that article and 10 others just fine. Maybe uncheck, save settings, refresh page, recheck, and save settings, refresh and see if it works?

**Comment by TesterMan247** [comment]
I'll try that and report back.
Thanks.
