### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by n-o-o-b** [iamadamdev/bypass-paywalls-firefox#164]
telegraph.co.uk
thetimes.co.uk

Both are supported by https://github.com/nextgens/anti-paywall.

**Comment by n-o-o-b** [comment]
Correction: The Telegraph does not currently work with Anti-Paywall. But The Times does. Before I get told off for not Googling these sites in Private Browsing, I would like to state that the New Statesman, which is supported by this add-on (Bypass Paywalls), has a paywall for me in Private Browsing. So I am not prepared to trust this method 100%.

**Comment by iamadamdev** [comment]
The first article you visit on newstatesman.com from private browsing shouldn't have any paywall. I didn't do anything special for that site, it works the same as all the others.

**Comment by iamadamdev** [comment]
Added in the latest version v1.5.2

**Comment by n-o-o-b** [comment]
@iamadamdev The first one didn't have a paywall, but subsequent ones did. Afaik. Or whatever the limit was.

Thank you!

P.S. These two sites aren't being unblocked for me. I've updated to latest version.

**Comment by iamadamdev** [comment]
Which article are you seeing a paywall on?
