### ISSUE TITLE
NKNews-Support would be awesome

### ISSUE THREAD

**Issue by 297998** [iamadamdev/bypass-paywalls-firefox#165]
Would it be possible to include http://www.dereferer.org/?http%3A%2F%2Fnknews%2Eorg%2F to this addon? I would be thrilled.

Keep up the good work!

**Comment by iamadamdev** [comment]
Unfortunately it won't work on those articles, you can test it yourself:
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by 297998** [comment]
I can not confirm that, as it works with this URL:
www.dereferer.org/?https://www.nknews.org/2019/04/kim-jong-un-praises-new-facilities-in-visit-to-newly-renovated-department-store/

Am So., 7. Apr. 2019 um 05:28 Uhr schrieb Adam <notifications@github.com>:
