### ISSUE TITLE
https://www.bloombergquint.com/bq-blue-exclusive/naresh-goyals-departure-from-jet-airwaysnecessary-but-not-sufficient#gs.2hb67g

### ISSUE THREAD

**Issue by vipuldsharma** [iamadamdev/bypass-paywalls-firefox#170]
https://www.bloombergquint.com/bq-blue-exclusive/naresh-goyals-departure-from-jet-airwaysnecessary-but-not-sufficient#gs.2hb67g

Please sir remove the paywall from this site, I will be highly indebted to you. Thanks

**Comment by chuckufarlie** [comment]
> 
> 
> https://www.bloombergquint.com/bq-blue-exclusive/naresh-goyals-departure-from-jet-airwaysnecessary-but-not-sufficient#gs.2hb67g
> 
> Please sir remove the paywall from this site, I will be highly indebted to you. Thanks

**Did you want to read that single article?** 

https://outline.com/87serj

**Comment by vipuldsharma** [comment]
No not only that but there are many more articles like this on bloombergquint.com and since Bloomberg Quint is a very good platform to stay updated, I requested Adam sir to remove the type of paywall paywall in the article which I posted, of the same site.

**Comment by vipuldsharma** [comment]
Please reply adam sir

**Comment by iamadamdev** [comment]
That is a premium article that cannot be bypassed in private mode either.
