### ISSUE TITLE
What data is accessed to install?

### ISSUE THREAD

**Issue by MTX281** [iamadamdev/bypass-paywalls-firefox#171]
"Add Bypass Paywalls requires your permission to: Access your data for all websites"

What data is accessed that needs permission and what is done with it?
Thanks.

**Comment by MTX281** [comment]
???

**Comment by MTX281** [comment]
??

**Comment by MTX281** [comment]
??

**Comment by iamadamdev** [comment]
It's only cause I'm too lazy to manually add every single site to the permissions array, so I did a default all sites. It only modifies cookies and headers on sites you want to bypass paywalls on.
