### ISSUE TITLE
Can't install add-on

### ISSUE THREAD

**Issue by nevadarain** [iamadamdev/bypass-paywalls-firefox#175]
I tried to install the add-on but was unsuccessful.  In firefox I allow the add-on but then it says, "failed to download because of a connection error". I am connected to the internet so i'm not sure why it's throwing this error.  Any help is much appreciated. Thank you.

**Comment by iamadamdev** [comment]
Restart computer and try again?

**Comment by xthursdayx** [comment]
Same issue here....

**Comment by nevadarain** [comment]
I completely forget.  I thought i updated this post. My apologies.  If you can't install on firefox, this is the fix.

1) within firefox, copy download url
2) open chrome and paste into address bar (this will download the firefox plugin using chrome to your desktop). I guess you can also just open chrome and go to the github pay wall firefox link. 
3) once downloaded just drag that file into firefox browser. Done!
