### ISSUE TITLE
New site request: Trustnodes

### ISSUE THREAD

**Issue by marcuswin** [iamadamdev/bypass-paywalls-firefox#178]
URL: https://www.trustnodes.com/

**Comment by iamadamdev** [comment]
Where are you seeing a paywall? I loaded 10+ articles just fine.

**Comment by marcuswin** [comment]
I tried to remove cookies, but it's not worked, incognito hasn't this paywall.

![Screenshot from 2019-04-08 12-30-14](https://user-images.githubusercontent.com/46599751/55713830-23dea280-59fa-11e9-8215-3fbe59ed6abd.png)

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?

![image](https://user-images.githubusercontent.com/36013816/56869283-aaf8b800-69b3-11e9-90b1-5226679c97b5.png)
