### ISSUE TITLE
The Economist Stopped Working <again>

### ISSUE THREAD

**Issue by jai434** [iamadamdev/bypass-paywalls-firefox#179]
Seem to have changed their algorithm. Please help!

**Comment by iamadamdev** [comment]
You can try hitting ESC once the article starts to load (or refresh and then hit ESC). Otherwise I don't have any fix at the moment.

**Comment by jai434** [comment]
Many thanks Adam. That works for now.

**Comment by ThisIsARandomPerson** [comment]
@iamadamdev Is it possible to add a fake sign-in cookie or something?

**Comment by icheyne** [comment]
I fixed this with Ublock Origin. Using [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering), block all inline scripts for economist.com.
![image](https://user-images.githubusercontent.com/389366/57178807-2e138580-6e6e-11e9-96ad-01276dd15e92.png)

**Comment by iamadamdev** [comment]
Please update to v1.5.4 and see if that fixes the issue.
