### ISSUE TITLE
The Australian doesn't render the page correctly with v1.5.2

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-firefox#180]
The Australian (https://www.theaustralian.com.au) doesn't render the page correctly when v1.5.2 extension is enabled. With it disabled, the page is rendered correctly.

Screenshot with extension enabled: https://imgur.com/Ei7XoMP
Screenshot with extension disabled: https://imgur.com/WpxWehQ

**Comment by iamadamdev** [comment]
Just refresh the page. I saw that sometimes too. If you turn off the extension then you can't view any articles...

**Comment by TesterMan247** [comment]
You stated before you edited your comments to try refreshing the page in 1.5.2. I did that, but the issue remains.

**Comment by iamadamdev** [comment]
You uninstalled and reinstalled the extension? Uncheck site, hit save, recheck site, hit save, refresh page?
It works fine for me (on first visit sometimes it doesn't load correctly, but refreshing fixes it for me).

**Comment by TesterMan247** [comment]
1.5.3 seems to be working correctly MOST of the time.
Any idea why you have to refresh the page sometimes?

**Comment by iamadamdev** [comment]
Please update to v1.5.4 and see if that fixes the issue.

**Comment by TesterMan247** [comment]
Works well so far after quick testing.
Thanks a lot.

If there are any more issues, I'll open another bug report.
Thanks again.
I appreciate all your hard work.
