### ISSUE TITLE
NY Times video broken

### ISSUE THREAD

**Issue by jeenuv** [iamadamdev/bypass-paywalls-firefox#181]
Video slurs and breaks on this page: https://www.nytimes.com/2019/04/06/health/drug-resistant-candida-auris.html. It works well without the extension.

**Comment by iamadamdev** [comment]
Video loads fine for me. Do you have other extensions installed?

**Comment by jeenuv** [comment]
For me, the video does load; it's the playback that's broken. I have a couple of more extensions installed, like LastPass, but nothing exotic. If I disable the bypass paywall extension, I can get the video playing back normally.

I wonder if this is because the Video is played back in blobs, and each of that goes through extension, thus inducing a delay.
