### ISSUE TITLE
Please add Der Spiegel

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [iamadamdev/bypass-paywalls-firefox#182]
http://www.spiegel.de/
https://www.spiegel.de/plus/#ref=plus-lhp
https://www.spiegel.de/plus/was-eltern-von-kleinkindern-alles-falsch-machen-koennen-a-00000000-0002-0001-0000-000163279560

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
