### ISSUE TITLE
Telegraph works with 1.5.2, not 1.5.3

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#183]
As the title says, version 1.5.2 works perfectly with https://www.telegraph.co.uk. Version 1.5.3 breaks it again.
Thanks in advance.

**Comment by iamadamdev** [comment]
Works fine for me, try hitting refresh?

**Comment by defrilitus** [comment]
You are absolutely right. I don't know what went wrong, but I've tried several times again and version 1.5.3 does work without any problem on the Telegraph. Apologies.

**Comment by defrilitus** [comment]
PS: I finally figured out the issue. You were right, again. If a page shows that it is "Premium Only", a quick refresh resolves the problem.
