### ISSUE TITLE
The Saturday Paper blocked

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-firefox#188]
When I go to the site The Saturday Paper (https://www.thesaturdaypaper.com.au/culture) I am blocked and the page does not load.

Screenshot: https://imgur.com/iSrSHiS

With the extension 1.5.3 disabled, the page loads up properly.

**Comment by Jarijari7** [comment]
Go to Google Chrome or Opera where you should have access to the site. Right click on an article and select copy link location. Go to outline.com and copy the url. That should give you access to an article.

**Comment by TesterMan247** [comment]
> Go to Google Chrome or Opera where you should have access to the site. Right click on an article and select copy link location. Go to outline.com and copy the url. That should give you access to an article.

No, you don't understand the issue.
The Saturday Paper works fine with Bypass Paywalls 1.5.3 disabled.
It's an issue with this extension that is causing the issue with the site.

**Comment by Jarijari7** [comment]
I'm no techie mate and don't understand the issue, just saying this is a way of accessing the site's content. You can also access the the pdf of the Saturday Paper by using a random 8-digit library loigin (without username or email address) at
http://library.pressdisplay.com/pressdisplay/viewer.aspx

**Comment by phly95** [comment]
Pick any number here if you need a number

https://www.random.org/strings/?num=10&len=8&digits=on&unique=on&format=html&rnd=new

**Comment by TesterMan247** [comment]
1. If I tick "The Saturday Paper" box.
Screenshot: https://imgur.com/2pQFngo

2. Then I go to the site The Saturday Paper (https://www.thesaturdaypaper.com.au/culture) I am blocked and the page does not load.
Screenshot: https://imgur.com/Qa6GqK3

3. If I untick "The Saturday Paper" box.
Screenshot: https://imgur.com/NnUZ7vZ

4. Then I go to the site The Saturday Paper (https://www.thesaturdaypaper.com.au/culture), the site is working correctly.
Screenshot: https://imgur.com/aZW3O29

Please fix the issue.

**Comment by iamadamdev** [comment]
Please update to v1.5.4 and see if that fixes the issue.

**Comment by TesterMan247** [comment]
Works well so far after quick testing.
Thanks a lot.

If there are any more issues, I'll open another bug report.
Thanks again.
I appreciate all your hard work.
