### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by Sneazzy** [iamadamdev/bypass-paywalls-firefox#190]
Hello,

L'Equipe is by far the biggest Sport-related site in France and releases a ton of quality content behind paywall. It would be great to see it added to the list.
https://www.lequipe.fr/Football/Article/Jacques-crevoisier-mohamed-salah-etait-en-surregime-a-liverpool/1007224
https://www.lequipe.fr/
Thanks in advance

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
