### ISSUE TITLE
A Request for The Atletic

### ISSUE THREAD

**Issue by berkbulgan** [iamadamdev/bypass-paywalls-firefox#191]
Today I've come upon another paywall witch is on The Atletic.
The exact site was https://theathletic.com/915423/2019/04/11/celtics-on-celtics-survey-players-reveal-the-lighter-side-of-their-teammates/ thaks for the great work btw

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
