### ISSUE TITLE
outline.com bookmarklet broken

### ISSUE THREAD

**Issue by kicksturns** [iamadamdev/bypass-paywalls-firefox#192]
bookmarklets that use outline.com recently (in the last week or two) stopped working when bypass paywalls is enabled.   Now a bookmarklet that directs to outline.com/thepaywalledpageyouwant will not display the full article as normal, just some title text and a blank page.  Disabling bypass paywall and the bookmarklet functions again.  

the bookmarklet:
javascript:(function()%7Bwindow.location.href %3D 'https%3A%2F%2Foutline.com%2F' %2B window.location.href%7D)()

**Comment by iamadamdev** [comment]
What are bookmarklets? What site does it not work on?
