### ISSUE TITLE
None of the articles on BloombergQuint seem to work in v1.5.3

### ISSUE THREAD

**Issue by paratheta** [iamadamdev/bypass-paywalls-firefox#196]
I can confirm that BQ Blue exclusive articles like [these](https://www.bloombergquint.com/bq-blue-exclusive/rajeev-thakkar-explains-when-is-the-right-time-to-buy-a-stock) worked a few days ago using the latest version of this addon but now they don't. When it comes to articles not under BQ Blue subscription, it's a hit-or-miss. Sometimes they work while displaying a message that "n free articles remaining" and sometimes they don't while showing "you have reached daily limit". I also tried disabling uBlock Origin and refreshing the page but that didn't help either.

**Comment by iamadamdev** [comment]
bloombergquint.com was never a supported site in the first place

**Comment by paratheta** [comment]
Well, in that case, can you add support for bloombergquint.com in this addon?

**Comment by iamadamdev** [comment]
You can try using https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/
