### ISSUE TITLE
Both The Times and The Telegraph Have Stopped Working

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#197]
Both https://www.thetimes.co.uk and https://www.telegraph.co.uk have stopped working.

**Comment by iamadamdev** [comment]
Still works fine for me. Make sure they are checked in options.

**Comment by defrilitus** [comment]
They are checked, but unfortunately still don't work: https://imgur.com/a/38L9MHJ

**Comment by iamadamdev** [comment]
Link to article?

**Comment by defrilitus** [comment]
https://www.telegraph.co.uk/technology/2019/04/28/inside-room-facebook-decides-23bn-people-can-cant-say/

**Comment by Connum** [comment]
Also not working for me. Another example URL: https://www.telegraph.co.uk/tv/0/lighten-jon-snow-game-thrones-dark/

I'm located in the EU if that matters.

**Comment by defrilitus** [comment]
The Telegraph (https://www.telegraph.co.uk) is now working again. Thanks! Much appreciated!
