### ISSUE TITLE
Bloomberg paywall bypass not working

### ISSUE THREAD

**Issue by lucassz** [iamadamdev/bypass-paywalls-firefox#198]
Example: https://www.bloomberg.com/opinion/articles/2018-02-22/harvard-alumni-cook-up-a-dumb-idea-for-its-endowment

The whole article is displayed temporarily, but then the paywall appears.

**Comment by iamadamdev** [comment]
Try using https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/

**Comment by lucassz** [comment]
@iamadamdev Nice catch, thank you! That seems to work.
