### ISSUE TITLE
Add german news sites

### ISSUE THREAD

**Issue by tzimon** [iamadamdev/bypass-paywalls-firefox#2]
I don't know whether you are able to bypass the following, would be nice if you could add them if it's possible:
[ZEIT Online](http://www.zeit.de/2018/17/handelsstreit-donald-trump-usa-china-europa)
[SZ.de](http://www.sueddeutsche.de/politik/tuerkei-nicht-gefangen-aber-auch-nicht-frei-1.3949384)

**Comment by iamadamdev** [comment]
Unfortunately it won't work for those sites.
