### ISSUE TITLE
New Site Request: Star Tribune

### ISSUE THREAD

**Issue by steveafrost** [iamadamdev/bypass-paywalls-firefox#200]
**Site**
startribune.com

**Description**
Paywall appears after 5-10 articles viewed. Loading in incognito removes paywall.

**Comment by steveafrost** [comment]
![reference](https://cl.ly/76e216f4138c/Screen%252520Shot%2525202019-04-24%252520at%2525203.00.49%252520PM.png)

**Comment by iamadamdev** [comment]
Local sites are not being added anymore. However you can always disable javascript on that site to easily bypass that paywall.
I recommend:
https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/
