### ISSUE TITLE
Business Insider Australia blocked

### ISSUE THREAD

**Issue by konomikitten** [iamadamdev/bypass-paywalls-firefox#202]
Similar to #188 when I try to access Business Insider Australia (https://www.businessinsider.com.au/) I get the following message:

````
Sorry, you have been blocked
You are unable to access businessinsider.com.au
````

Disabling the extension allows the web site to work and when I enabled it again I get the blocked message. Happy to provide more info.

**Comment by iamadamdev** [comment]
Please update to v1.5.4 and see if that fixes the issue.

**Comment by konomikitten** [comment]
v1.5.5 has fixed the issue for me, thanks for your time.
