### ISSUE TITLE
Disabled automatically on Firefox 66.0.3 (64-bit) Linux

### ISSUE THREAD

**Issue by jibran-locusnine** [iamadamdev/bypass-paywalls-firefox#203]
today this addon, along with many other addons was disabled automatically on Firefox 66.0.3 (64-bit) Linux.   
Trying to install from the link on readme.md says it is corrupt.  
Thanks for your work on this addon!

![bypass](https://user-images.githubusercontent.com/48667686/57176578-260c1380-6e77-11e9-987f-151bc4f271a0.png)

**Comment by ari1010** [comment]
Also on Firefox 60.0.1 64bits (Windows)

**Comment by lesterlxy** [comment]
I believe this is part of the new signing requirements. You can easily bypass it by using `about:config` and setting `xpinstall.signatures.required` to `false`.

**Comment by tom1417** [comment]
Looks like firefox had an issue with one of their certificates. All my addons have been disabled. Hopefully they resolve it soon

**Comment by iamadamdev** [comment]
https://twitter.com/firefox/status/1124677072771665920

**Comment by jibran-locusnine** [comment]
I guess, I should close this issue.

**Comment by iamadamdev** [comment]
Fixed in Firefox 66.0.4
https://discourse.mozilla.org/t/fixed-certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
