### ISSUE TITLE
ESPN+

### ISSUE THREAD

**Issue by berkbulgan** [iamadamdev/bypass-paywalls-firefox#206]
Site: www.espn.com

Link: http://www.espn.com/nba/insider/story/_/id/26695230/what-happens-kyrie-ad-decide-boston-future-now

Description: ESPN+ requires subsciption for articles

**Comment by iamadamdev** [comment]
That's a premium article.
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
