### ISSUE TITLE
add Inman news site

### ISSUE THREAD

**Issue by freelancer65** [iamadamdev/bypass-paywalls-firefox#208]
As real estate sites go, this one (inman.com) is pretty plugged in to what is going on in the industry. The /amp/  bypass used to work - then they plugged that. Could this site be added to the paywall bypass list?

Thanks.

**Comment by iamadamdev** [comment]
Unfortunately some of those are behind a hard paywall.

**Comment by freelancer65** [comment]
Ok - thanks for checking.
