### ISSUE TITLE
The Washington Post appears broken with version 1.30 and above

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#21]
As the title says, washingtonpost.com doesn't work with version 1.30 and above. Oddly enough, it works for a while after installing the new version before reverting to the paywall (maybe until Firefox is restarted?), which is why it took some time for me to realise that the problem was the new version and not a conflict with another extension. Hope you can fix this (for now I'm sticking to version 1.29); in the meantime, many thanks for all the pleasure this add-on has given me!

**Comment by brandonsavage** [comment]
I can confirm this as well, but I think WaPo is using new mechanisms to enforce their paywall so you may have to do some digging. I'll investigate too and post anything I find.

**Comment by defrilitus** [comment]
@brandonsavage I doubt that the Washington Post is using new paywall mechanisms, as Bypass Paywalls 1.29 still works perfectly on washingtonpost.com with both Chrome and Firefox.

**Comment by iamadamdev** [comment]
Try now with v1.3.4

**Comment by defrilitus** [comment]
@iamadamdev Works perfectly. Thank you.
