### ISSUE TITLE
Glassdoor login broken

### ISSUE THREAD

**Issue by unleashit** [iamadamdev/bypass-paywalls-firefox#210]
Can't login to Glassdoor when Glassdoor is enabled in the plugin options. The response from Glassdoor is a 403 (assuming because it couldn't set the cookie) on every login request.

Look me quite a while to troubleshoot what was causing this!

**Comment by iamadamdev** [comment]
FTM: "Selected sites will have their cookies cleared and referer set to Google. You should uncheck sites you have an account with or else you will be logged out at every visit."

**Comment by unleashit** [comment]
@iamadamdev thanks for your extremely quick reply. I didn't notice that. Perhaps it could be better emphasized? I assume you mean the plugin description is where that phrase can be found, but I don't see in here on the Github readme.

In any case thanks for your work! My motive isn't to complain, but my first inclination was to blame ublock, privacy badger etc. (didn't occur to me that Glassdoor would even be a consideration for this extension).
