### ISSUE TITLE
WSJ not working and never will, just take it off list of sites

### ISSUE THREAD

**Issue by johnda3** [iamadamdev/bypass-paywalls-firefox#212]
Unless you can get around the WSJ paywall with this program, which I don't see how, doesn't it seem better to just remove the WSJ from the list of sites it can access rather than claiming it can access a site it's never going to be ale to.

**Comment by iamadamdev** [comment]
Do you have WSJ checked in options?
This addon has always been working for WSJ and still is. Tested on Firefox for Windows and macOS.

![image](https://user-images.githubusercontent.com/36013816/57668431-236a9600-75bc-11e9-858f-b532d0445ed0.png)

**Comment by kg27r** [comment]
Working perfectly on Android Firefox
https://www.wsj.com/articles/uber-and-lyft-get-creative-with-numbers-but-investors-arent-blind-to-the-losses-11557826202?mod=rsswn

BTW: I'm considering changing my Android default browser just for this add-on.
