### ISSUE TITLE
www.foreignaffairs.com

### ISSUE THREAD

**Issue by kg27r** [iamadamdev/bypass-paywalls-firefox#216]
Not working on Windows Firefox and Chrome. Getting only beginning of article followed by "Register to read one free article a month." or "Register to keep reading or subscribe for unlimited access"
Also Chrome has navbar issue.
Examples:
https://www.foreignaffairs.com/articles/2019-04-16/time-different
https://www.foreignaffairs.com/articles/iran/2019-05-09/art-new-iran-deal
https://www.foreignaffairs.com/articles/europe/2019-05-13/viktor-orban-wants-trumps-help-european-elections
https://www.foreignaffairs.com/articles/russian-federation/2017-02-13/trump-and-russia

**Comment by iamadamdev** [comment]
Those are all premium articles behind a hard paywall. Or they changed their algo.
