### ISSUE TITLE
site add request please

### ISSUE THREAD

**Issue by xmanore** [iamadamdev/bypass-paywalls-firefox#218]
followed your test instructions, site loaded w/o paywall.  site is:

www.adweek.com

thanks!

**Comment by iamadamdev** [comment]
Not sure why but I am still getting a paywall after adding it and even blocking JS. But using a turn off JS addon only does work. Try https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/

**Comment by xmanore** [comment]
Thanks!
