### ISSUE TITLE
Bloomberg appears broken with version 1.3.1

### ISSUE THREAD

**Issue by esteves023** [iamadamdev/bypass-paywalls-firefox#22]
It's working on Chrome but not on Firefox.

**Comment by iamadamdev** [comment]
Try latest v1.3.4

**Comment by SergeGardien** [comment]
On Bloomberg I can read recent articles but not archived ones of few years back.

For example I cannot read this:
[https://www.bloomberg.com/news/articles/2012-07-23/asia-hedge-funds-put-returns-ahead-of-cash-as-investors-hold-off](https://www.bloomberg.com/news/articles/2012-07-23/asia-hedge-funds-put-returns-ahead-of-cash-as-investors-hold-off)
but I can read this other one:
[https://www.bloomberg.com/news/articles/2018-08-30/google-and-mastercard-cut-a-secret-ad-deal-to-track-retail-sales](https://www.bloomberg.com/news/articles/2018-08-30/google-and-mastercard-cut-a-secret-ad-deal-to-track-retail-sales)

I don't understand if this is my issue or a problem with bypass-paywalls. I use the addon on both, Firefox and Google Chrome and I have the same result.

**Comment by SergeGardien** [comment]
Pardon me, I have just read this [https://github.com/iamadamdev/bypass-paywalls-chrome/issues/26](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/26).

That's probably the reason I cannot read old articles.
