### ISSUE TITLE
No longer working with Washington Post

### ISSUE THREAD

**Issue by matbech** [iamadamdev/bypass-paywalls-firefox#221]
Complains about private mode, even though private mode is not enabled.

"We noticed you’re browsing in private mode."

**Comment by seascape** [comment]
I came to check about this as well.

My experience was that in regular mode with uBlock Origin and Bypass Firewalls I got a "We noticed you're blocking ads" nag (I was unsuccessful in bypassing it, too). Using a Private Window with both add-ons resulted in a "We noticed you're browsing in private mode" nag.

**Comment by sdean7855** [comment]
Same here.  With Adblock Plus and BP, I get a a "We noticed you're blocking ads" nag.

**Comment by tejasvi** [comment]
Install Nano Defender (to block blockadblock)

**Comment by kristofferR** [comment]
@tejasvi is correct. This issue has nothing to do with this extension, which bypasses paywalls, it's because you guys haven't installed a proper anti-anti-adblock extension (like Nano Defender).

**Comment by final-wave** [comment]
I do have anti-adblocker stuff in place but it has broken sometimes. Will look into Nano Defender.

**Comment by iamadamdev** [comment]
Works fine in the U.S. Try connecting to a U.S. proxy using https://addons.mozilla.org/en-US/firefox/addon/anonymox/
