### ISSUE TITLE
Site request: https://www.theinformation.com

### ISSUE THREAD

**Issue by SeriousHoax** [iamadamdev/bypass-paywalls-firefox#223]
Here is an example article
 https://www.theinformation.com/articles/former-apple-chip-engineers-leave-google?

**Comment by iamadamdev** [comment]
Seems to be a hard paywall.

**Comment by SeriousHoax** [comment]
@iamadamdev So it's not possible to bypass it?

**Comment by iamadamdev** [comment]
Most likely not.

**Comment by frankzhangming** [comment]
it's a good website,can you bypass it?
