### ISSUE TITLE
Add McClatchy sites

### ISSUE THREAD

**Issue by cybertoad1** [iamadamdev/bypass-paywalls-firefox#224]
Major market dailies include:
    The Charlotte Observer (Charlotte, North Carolina)
    The Idaho Statesman (Boise, Idaho)
    The Kansas City Star (Kansas City, Missouri)
    The Miami Herald (Miami, Florida)
    The News & Observer (Raleigh, North Carolina)
    The Sacramento Bee (Sacramento, California)
    Fort Worth Star-Telegram (Fort Worth, Texas)

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
