### ISSUE TITLE
Bypass Paywall

### ISSUE THREAD

**Issue by beijinglg** [iamadamdev/bypass-paywalls-firefox#226]
Please add The Straits Times https://www.straitstimes.com/global to the Firebox bypass extension. The Straits Times is a major broadsheet in Singapore and the South East Asia region.

**Comment by iamadamdev** [comment]
Most articles on that site are not behind a paywall. Premium ones are behind a hard paywall which cannot be bypassed.

**Comment by beijinglg** [comment]
Thank you.
