### ISSUE TITLE
No issues, just kudos

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#227]
I have no issues at all, but just wanted to say "thank you" for this add-on. I certainly don't take this extension for granted, especially as I know how my browsing experience would be poorer without it 😉 I would be perfectly happy to contribute to keep things going. Please let us know how to do so 😇

**Comment by iamadamdev** [comment]
I am not asking for donations or anything like that, all I ask is that you star this repo.
I do appreciate your words of encouragement though. 🙂

**Comment by defrilitus** [comment]
I meant every word. And I have starred the repo.
