### ISSUE TITLE
Paywall in Haaretz comes up when Adguard Adblocker is on.

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#23]
Hello? I appreciate your support for Bypass Paywall.

When I opened the second article on Haaretz.com, paywall comes up.
I use Adguard Adblocker in order to remove ads. I found that it is recommended to use Bypass Paywall add-on with Ublock origin...
but can you please let us bypass paywall on Haaretz.com when Adguard Adblocker is on?

Thank you for your kind answer.

**Comment by iamadamdev** [comment]
Try latest v1.3.4

**Comment by mickeyseo** [comment]
I choose to use uBlock Origin instead of Adguard Adblocker as your recommendation. Thank you!
