### ISSUE TITLE
Automatically select new sites when extension is updated

### ISSUE THREAD

**Issue by articlecat** [iamadamdev/bypass-paywalls-firefox#230]
It would be nice if Bypass Paywalls automatically selected new sites when the extension is updated. Currently, new sites are unselected, and users have to go into the extension settings from time to time to select them if they want the extension to have maximum coverage.

I understand that some users might not want this, since they won't be able to log in to selected sites. A checkbox that allows users to opt in/out of the automatic selection should satisfy everyone.

**Comment by iamadamdev** [comment]
Feel free to submit a PR for that change.
