### ISSUE TITLE
Not working for Business Insider

### ISSUE THREAD

**Issue by quizzicus** [iamadamdev/bypass-paywalls-firefox#232]
v1.5.5. Demands that I sign up for Business Insider Prime regardless of whether I'm using private mode/uBlock Origin.

**Comment by iamadamdev** [comment]
Still works for me.
What article?
Usually premium articles cannot be bypassed as they are behind a hard paywall.

**Comment by vhoanghac** [comment]
Let's check this article: https://www.businessinsider.com/next-recession-stanley-druckenmiller-best-forecaster-investing-advice-2019-6

**Comment by tejasvi** [comment]
It isn't behind a hard paywall but requires clicking 'Read full story'.

**Comment by iamadamdev** [comment]
I can bypass it by disabling javascript but then all the images on the main site won't load.
