### ISSUE TITLE
Please consider adding this site

### ISSUE THREAD

**Issue by AmericanTruckingDev** [iamadamdev/bypass-paywalls-firefox#233]
https://www.richmond.com/news/plus/after-virginia-beach-shooting-northam-outlines-gun-control-measures-he/article_0134b8dc-9f3e-5226-8bb6-0342810aace7.html

This is the Richmond Times-Dispatch one of Warren Buffet's newspapers

Thank you,
Tom

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
