### ISSUE TITLE
Some articles on the Toronto Star are paywalled

### ISSUE THREAD

**Issue by vic958420** [iamadamdev/bypass-paywalls-firefox#234]
https://www.thestar.com/business/2019/06/04/the-raptors-are-now-the-most-valuable-sports-franchise-in-canada-experts-say.html

![thestarnotworking](https://user-images.githubusercontent.com/38735851/58990804-5c221780-87d6-11e9-9c8e-08632f553cea.JPG)

**Comment by iamadamdev** [comment]
I can fix it but then you won't get images on the main page.
