### ISSUE TITLE
The widget in hbr.org doesn't work.

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#24]
Hello? Thank you for your hard work.

I opened articles in hbr.org. I clicked icons in the widget on HBR's article, but none of them worked. I think Bypass Paywall add-on blocks the widget on HBR website from working. Can you please fix this problem?

Here is a screenshot.
https://drive.google.com/file/d/1TgpGguXYJi4_6JWWFkmJuLCykvra56eN/view?usp=sharing

Thank you.

**Comment by iamadamdev** [comment]
Try latest v1.3.4
