### ISSUE TITLE
Site request: Pittsburgh Post-Gazette

### ISSUE THREAD

**Issue by amill18** [iamadamdev/bypass-paywalls-firefox#240]
Example article below is paywalled in a regular window, but accessible (via google search) in a private window. Thanks in advance!

https://www.post-gazette.com/business/tech-news/2019/06/12/Facebook-Mark-Zuckerberg-video-deepfake-Instagram-Pelosi/stories/201906120160

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
Turn off uBlock Origin and you should be able to load that article along w/ cookie removal.
