### ISSUE TITLE
Please add telegraaf.nl

### ISSUE THREAD

**Issue by patrickTingen** [iamadamdev/bypass-paywalls-firefox#241]
Hi, thanks for your awesome plugin. The Dutch site for Telegraaf (largest paper in the Netherlands) also uses a paywall that can be passed according to your criteria. I checked it in an incognito window and it loaded just fine. 

The url is www.telegraaf.nl
Example link: https://www.telegraaf.nl/nieuws/1769488701/beeld-van-tjeerd-zijn-zwaar-verminkte-gezicht-achtervolgt-mij

PS have you considered allowing users to add their own site?

**Comment by iamadamdev** [comment]
Not sure why but on Firefox trying the bypass methods it doesn't prompt to accept cookies and I keep getting this paywall:
![image](https://user-images.githubusercontent.com/36013816/59959514-c04b0980-946d-11e9-8b20-6e379073965b.png)

It works fine on Chrome though.
https://github.com/iamadamdev/bypass-paywalls-chrome

> PS have you considered allowing users to add their own site?

It doesn't work like that. There are different techniques for different sites.
