### ISSUE TITLE
Bypass not working

### ISSUE THREAD

**Issue by sguser1** [iamadamdev/bypass-paywalls-firefox#249]
I installed Bypass Paywalls and uBlock Origin in my Firefox 67.0.4. They are both Allowed in Private Windows. All websites are checked on the Options Page. On the NY Times and LA Times websites I still receive the "You're in private mode" message. 

I am based in Singapore.

What could I have done wrong that it's not working???

Please help!

**Comment by iamadamdev** [comment]
Try non-private window.. also NYT should be fine w/ just uBlock Origin installed.
