### ISSUE TITLE
Request bypass paywall

### ISSUE THREAD

**Issue by jher000** [iamadamdev/bypass-paywalls-firefox#251]
NT News
Hobart Mercury
Canberra Times
Townsville Bulletin
The West Australian
Newcastle Herald

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
