### ISSUE TITLE
Washington Post does not work (stuck in a refresh-loop?)

### ISSUE THREAD

**Issue by DanielValahul** [iamadamdev/bypass-paywalls-firefox#252]
Just as the title says, if for example i click on a washington post article from reddit it will reach the GDPR message but then it will enter this weird refresh loop. The page itself doesnt refresh but the button for refresh in firefox will appear as it is. Also the article never loads. 
EDIT: It appears that it works if i disable Bypass Paywalls for it

**Comment by s1shed** [comment]
Unfortunately I have the same problem.

In the console logs I see

```
Navigated to https://www.washingtonpost.com/?
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn-api.arcpublishing.com/v1.0/loxodo/datapoint/save. (Reason: CORS request did not succeed).
Navigated to https://www.washingtonpost.com/?
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn-api.arcpublishing.com/v1.0/loxodo/datapoint/save. (Reason: CORS request did not succeed).

```

**Comment by iamadamdev** [comment]
Works fine for me still.
Are you guys all located in the EU?

**Comment by iamadamdev** [comment]
Have you tried v1.5.5? Does that version have this problem too?

**Comment by s1shed** [comment]
I am in the EU. 

With v1.5.5 the GDPR prompt goes away after I manually click it away. The GDPR prompt is displayed each time a new article is loaded.

**Comment by s1shed** [comment]
I see that Chrome is able to automatically handle the GDPR prompt with the version contained within https://github.com/iamadamdev/bypass-paywalls-chrome/archive/master.zip

**Comment by iamadamdev** [comment]
Interesting, I will remove the GDPR auto click for Firefox then and that should fix the issue.

**Comment by iamadamdev** [comment]
Is it fixed in v1.5.7 now?

**Comment by s1shed** [comment]
> Is it fixed in v1.5.7 now?

Yes, there's no reloading of the page in a loop. Thank you for this incredibly useful addon.

(No promises since I don't know Javascript, but I'll try debugging this to find the solution for the GDPR bypass.)

**Comment by kristofferR** [comment]
Whoops. The auto GDPR bypass script was simply clicking through too fast for Firefox to handle, I've added a timeout that solves it. Here's the PR:
https://github.com/iamadamdev/bypass-paywalls-firefox/pull/257

I will also test and submit the improvement to the Chrome extension too.

**Comment by iamadamdev** [comment]
@kristofferR But that doesn't explain the reloading of the page does it? Were you able to repro s1shed's reloading issue before you added the delay?

**Comment by kristofferR** [comment]
Yeah, it just reloaded wildly in FX until I added the timeout. Now it works fine, at least for me.

**Comment by iamadamdev** [comment]
@kristofferR Are you located in EU too?

**Comment by kristofferR** [comment]
Yup, that's why I've created the GDPR bypass script (as clicking through the warning on every single Washingtonpost.com page is massively annoying).

**Comment by s1shed** [comment]
> Yup, that's why I've created the GDPR bypass script (as clicking through the warning on every single Washingtonpost.com page is massively annoying).
> 
> It seems the previous lack of a timeout clicked the GDPR page buttons too fast for Firefox to handle, leaving it stuck endlessly waiting for the auto clicking to stop before it could load the next page.

Since the timeout was added the GDPR bypass has been working wonderfully.

**Comment by magnolia1234** [comment]
Locking the wp_gdpr cookie with cookie-manager addon also works fine.
