### ISSUE TITLE
Please add Mosaic Magazine

### ISSUE THREAD

**Issue by benlevy0** [iamadamdev/bypass-paywalls-firefox#254]
[Example article.](https://mosaicmagazine.com/picks/history-ideas/2019/06/digging-in-the-golan-for-new-testament-history-archaeologists-find-a-ruin-from-the-time-of-king-david/)

Currently I just use [this extension](https://addons.mozilla.org/en-US/firefox/addon/remove-cookies-button-ver1x/) to clear the cookies each time I encounter the paywall, but it'd be nice to have it done automatically.

**Comment by iamadamdev** [comment]
Try my extension, same thing though.
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
