### ISSUE TITLE
Irish Times

### ISSUE THREAD

**Issue by AccringtonLaurel** [iamadamdev/bypass-paywalls-firefox#255]
Hi, I can't get the Irish Times to work - I get paywall notices. (Works fine though on other sites like NY Times, etc.) Thanks.

**Comment by iamadamdev** [comment]
Which article?

**Comment by AccringtonLaurel** [comment]
Here is an example: [https://www.irishtimes.com/opinion/stephen-collins-the-virtual-silence-on-shatter-s-hounding-from-office-is-odd-1.3939449?mode=sample&auth-failed=1&pw-origin=https%3A%2F%2Fwww.irishtimes.com%2Fopinion%2Fstephen-collins-the-virtual-silence-on-shatter-s-hounding-from-office-is-odd-1.3939449](url)
Yes, I am using uBlock Origin, and a couple of other addons (Decentraleyes, FB Container) but I still get the paywall when they are temporarily disabled.

**Comment by iamadamdev** [comment]
Looks like they have changed their algo, I will remove the site.
