### ISSUE TITLE
bypass paywall add-on doesn't work with uBlock Origin in Haaretz.com

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#26]
bypass paywall add-on doesn't work with uBlock Origin in Haaretz.com

Can you please fix this problem?

**Comment by iamadamdev** [comment]
Try latest v1.3.4

**Comment by mickeyseo** [comment]
Thank you! it works well with uBlock Origin in Haaretz!
