### ISSUE TITLE
News-Gazette no longer works

### ISSUE THREAD

**Issue by kstev99** [iamadamdev/bypass-paywalls-firefox#260]
News-Gazette recently changed their format and no longer works after 5 pages.  I can still google the articles and go to them in that manner

**Comment by iamadamdev** [comment]
I just loaded 10+ articles no problem. Which one are you having an issue with?
Do you have uBlock Origin installed?

**Comment by kstev99** [comment]
Strange, but right after they changed to a new format I was limited to 5 articles, but now a few days later your extension seems to be working as always.  Thanks for the quick response and bringing to my attention that the website now works.
