### ISSUE TITLE
Repubblica.it stuck in a refresh loop

### ISSUE THREAD

**Issue by ildoc** [iamadamdev/bypass-paywalls-firefox#262]
when I click on paywalled links (every links from https://rep.repubblica.it/pwa/) the pwa seems to start loading but the browser start refreshing like there's no tomorrow

I didn't find any console warning or errors though...

**Comment by iamadamdev** [comment]
I clicked on 5 articles from the home page and they all loaded fine. I saw the pwa page then it redirect to /ws/ no problem. 
E.g., I was able to load https://rep.repubblica.it/ws/detail/commento/2019/07/01/news/istat_occupazione_quello_che_i_dati_non_dicono_sull_economia-230104295/ w/o any issues.

**Comment by iamadamdev** [comment]
Maybe a GDPR issue cause you are in the EU? Maybe try a U.S. proxy and see if it fixes it? Try https://addons.mozilla.org/en-US/firefox/addon/anonymox/?src=search
