### ISSUE TITLE
Issue with Nikkei Asian Review

### ISSUE THREAD

**Issue by ParadoxicalParadox** [iamadamdev/bypass-paywalls-firefox#266]
Nikkei Asian Review limiting number of available articles per month.
Issue is found on the latest version of Firefox, 68.0.
Bypass-Paywalls is installed alongside Decentraleyes, Privacy Badger, Smart HTTPS, Nano Adblocker and Nano Defender.

FIrefox content blocking settings:
Trackers in all windows
Cookies: Third party trackers
Cryptominers
Fingerprinters

Manually clearing cookies of Nikkei Asian Review resets the limit counter.

**Comment by iamadamdev** [comment]
https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/

**Comment by ParadoxicalParadox** [comment]
What I'm doing now is using Forget Me Not and disallowing the website to ever set cookies as a workaround, thanks for the response though!
