### ISSUE TITLE
WAPO Again!

### ISSUE THREAD

**Issue by pjpreilly** [iamadamdev/bypass-paywalls-firefox#269]
1.5.8 is not working again! Private browsing popoup in Waterfox 56.2.12 on os x & Linux.

**Comment by pjpreilly** [comment]
..Looks like a Waterfox issue though unless BP can help with this.

**Comment by pjpreilly** [comment]
Anti-paywall seems to work where BP doesn't.
https://github.com/nextgens/anti-paywall/releases

**Comment by iamadamdev** [comment]
I just loaded 10+ wapo articles just fine. This is Bypass Paywalls for Firefox.

**Comment by pjpreilly** [comment]
Anti-paywall seems to work where BP doesn't.
https://github.com/nextgens/anti-paywall/releases

**Comment by pjpreilly** [comment]
It wasn't working on firefox ESR 52.9.0 too. The last ESR for os x Lion.

**Comment by iamadamdev** [comment]
I'm on Firefox Quantum 68. Works fine on macOS.

**Comment by iamadamdev** [comment]
Are you located in the EU?

**Comment by pjpreilly** [comment]
No in USA, I had to remove anti-paywall, it was saturating the processor on macbook 4,1 os x Lion.

**Comment by pjpreilly** [comment]
I'm running Waterfox Classic in this oldster. It's Based on firefox 56.

**Comment by iamadamdev** [comment]
Does it work after you removed anti paywall?
Based on Firefox means there could be differences that break it.. I am only testing this on the official Firefox.

**Comment by pjpreilly** [comment]
No, it thinks I'm Private Browsing w/wout your extension... can/should I test a different site to see if the extension is working there?

**Comment by iamadamdev** [comment]
wsj.com
