### ISSUE TITLE
how to bypass theinformation

### ISSUE THREAD

**Issue by frankzhangming** [iamadamdev/bypass-paywalls-firefox#270]
https://www.theinformation.com/,this is a good website,can you bypass it?

**Comment by iamadamdev** [comment]
Did you try following the instructions here? https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by frankzhangming** [comment]
I have installed your extention, but cannot bypass theinformation.

Adam <notifications@github.com> 于 2019年7月20日周六 03:54写道：

**Comment by iamadamdev** [comment]
That's because it's not a supported site yet.
Please read the instructions https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by frankzhangming** [comment]
I see, can you list it as a supported site?because it's a good news site.

Adam <notifications@github.com> 于 2019年7月20日周六 06:34写道：

**Comment by iamadamdev** [comment]
Site does not work.
