### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by swifterslb** [iamadamdev/bypass-paywalls-firefox#271]
Could you please see if you can add Initium Media (https://theinitium.com/, a Hong Kong-based site) to your wonderful add-on? Thanks a lot.

**Comment by iamadamdev** [comment]
Did you try following the instructions here? https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by iamadamdev** [comment]
Does not work.
