### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by rikkdekkard** [iamadamdev/bypass-paywalls-firefox#278]
Hello.

Would you please consider adding support for [Gazeta Wyborcza](http://wyborcza.pl/0,0.html)? It's the biggest newspaper in Poland an a member of Leading European Newspaper Alliance, so it hopefully qualifies as 'major'.
Opening articles via a search engine in private mode seems to work with regular news that aren't behind a hard paywall.

**Comment by iamadamdev** [comment]
Can you give me an article to test it on? All the ones I tested through google search incognito still showed me a paywall.

**Comment by rikkdekkard** [comment]
Yes, it seems like in the time since I opened this issue they have hardened their paywall and very few articles can be accessed by the "google-incognito" mode now. So few that it's hardly worth the bother.

Sorry for the inconvenience, closing this now.
