### ISSUE TITLE
Request for paywall circumvention help from one of the poorest states in the country. WV!

### ISSUE THREAD

**Issue by BillSohonage** [iamadamdev/bypass-paywalls-firefox#281]
I am a small non-profit director who would love to be up on the news throughout the state of WV, but alas cannot afford digital access to the states local newspapers. As a conglomerate the Charleston Gazette has most of the major state papers packaged together digitally, using an entity " Powered by BLOX Content Management System from TownNews.com."

I would love to be able to bypass this paywall, especially since the billionaire newspaper owner, is making most of his nest egg off of the fracking industry, I feel guilty giving him another dime, as I live in a community despoiled by the fracking industry.

**Comment by iamadamdev** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/
