### ISSUE TITLE
Add Nautilus

### ISSUE THREAD

**Issue by SebastianOner** [iamadamdev/bypass-paywalls-firefox#283]
[Nautilus](http://nautil.us/) is a very cool website I would like to have added

**Comment by iamadamdev** [comment]
Did you try https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles and
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by SebastianOner** [comment]
When I open a private window it works, but not with the cookie-remover addon
