### ISSUE TITLE
New release 1.5.8

### ISSUE THREAD

**Issue by ari1010** [iamadamdev/bypass-paywalls-firefox#287]
When I go to options to save selected sites, no sites at all are listed.

I've just checked telegraph.co.uk and irishtimes.com and bypass is no longer working.

Is it just me?

**Comment by ari1010** [comment]
Sorry....problem solved.

Ublock origin was removed in a Firefox update for some reason. One that was reinstalled, everything is back to normal.

**Comment by ari1010** [comment]
Although I see you have removed the 'irishtimes'. Was that deliberate?

**Comment by iamadamdev** [comment]
Yes it was no longer working.
