### ISSUE TITLE
Add new sites to existing list

### ISSUE THREAD

**Issue by Vishu-github** [iamadamdev/bypass-paywalls-firefox#289]
Hi, Can you please add the following news sites to your existing list. 
1. **Granta magazine** issues.(https://granta.com/cousins/)
2. **Project syndicate on point** issues (https://www.project-syndicate.org/onpoint/what-s-next-for-china-s-political-economy-by-kevin-rudd-2019-08?barrier=accesspaylog)

I have tried to bypass these sites through various means(archive.is, outline etc), but got failed each time. It would be great if you could help me out with this. 

Thanks in advance!

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
