### ISSUE TITLE
Can you please add www.bordermail.com.au

### ISSUE THREAD

**Issue by Axsnsmash** [iamadamdev/bypass-paywalls-firefox#29]
Can you please add www.bordermail.com.au thank you
And www.theaustralian.com.au just to keep up with your competitors Anti paywall

**Comment by iamadamdev** [comment]
Which competitor has bypassed it?
The simple google referral trick won't work for those sites.
There are some other methods I can try.

**Comment by Axsnsmash** [comment]
Hi thanks for getting back to me..
Here is the link to Anti paywall that has www.theaustralian.com.au listed
https://github.com/nextgens/anti-paywall
The bordermail.com.au is a newly created paywall... I will have a look at the code also to see if I can see any ideas..
Thanks awaiting you reply..
Cheers
