### ISSUE TITLE
New Site Request

### ISSUE THREAD

**Issue by kweeheinthu** [iamadamdev/bypass-paywalls-firefox#292]
Need this new site to be added https://theathletic.com/

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
?

**Comment by kweeheinthu** [comment]
Yea can’t bypass. https://theathletic.com/1160326/2019/08/26/paul-pogba/
