### ISSUE TITLE
Please add Caravan also

### ISSUE THREAD

**Issue by rakhekchai** [iamadamdev/bypass-paywalls-firefox#294]
Hi,

Thank you so much for making this resource. I was wondering if you could add https://caravanmagazine.in/. It's this really popular and amazing online new resource. 

Regards

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
?
