### ISSUE TITLE
Doesn't work with bostonglobe.com

### ISSUE THREAD

**Issue by scienceguyroy** [iamadamdev/bypass-paywalls-firefox#297]
The bypass of the paywall works, but you can't see the article.

**Comment by scienceguyroy** [comment]
You lose the article.

**Comment by iamadamdev** [comment]
Thanks for bringing it to my attention, I will remove it in the next version.
For now just uncheck it and you can read the articles until you hit the limit.
Install https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/
then cilck the cookie icon to remove the cookies and refresh the page to continue reading the article.
