### ISSUE TITLE
daily telegraph australia - paywall

### ISSUE THREAD

**Issue by brettderfg** [iamadamdev/bypass-paywalls-firefox#298]
can you please build the extension for this newspaper.

dailytelegraph.com.au

**Comment by iamadamdev** [comment]
Did you try 
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
?

**Comment by brettderfg** [comment]
Yes it doesn’t get past. The daily telegraph Australia is not listed.

Brett Ferguson

[cid:image001.jpg@01D3FDA5.BEAC9950]
HSIE Teacher
The Illawarra Grammar School
[signature_1586378633]
Western Avenue, Wollongong NSW 2500 
PO Box 225 Figtree NSW 2525 
Direct: 02 4220 0201 | Fax: 02 4220 0201| Email: bferguson@tigs.nsw.edu.au<mailto:bferguson@tigs.nsw.edu.au>
www.tigs.nsw.edu.au<http://www.tigs.nsw.edu.au/>

[signature_2087816064]
