### ISSUE TITLE
hbr.org 's widget still doesn't work.

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#30]
Hello? Thank you for your hard work.

I opened articles in hbr.org. I clicked icons in the widget on HBR's article, but none of them worked. I think Bypass Paywall add-on blocks the widget on HBR website from working. Can you please fix this problem?

Here is a screenshot.
https://drive.google.com/file/d/1TgpGguXYJi4_6JWWFkmJuLCykvra56eN/view?usp=sharing

Thank you.

-----------------------------------------
I downloaded the latest version (1.3.4), but the problem still exists. I disable uBlock Origin for hbr.org ,but this change doesn't make any effect.

**Comment by iamadamdev** [comment]
Loads fine for me on Chrome and Firefox. Try clearing your hbr cookies?

**Comment by mickeyseo** [comment]
I have tried clearing all cookies in Firefox, but it doesn't fix the problem. Instead, I don't use 'private browsing mode.' Now, I can adjust the text size in HBR.org.
Thank you!

Here is a screenshot.
https://drive.google.com/file/d/1WLyDc0W-7t3DWfpUwB5cKN5myVoh5N0K/view?usp=sharing

**Comment by iamadamdev** [comment]
It is not designed to work in private mode.
Does it work in normal mode?

**Comment by mickeyseo** [comment]
1. I can adjust the text size in normal mode, but I cannot read a full article. The subscription suggestion notification is found at the end of the article.
2. I cannot adjust the text size in private mode, but I can read a full article. The subscription suggestion doesn't show in an article.

Here is a screen video.
https://drive.google.com/file/d/1Gku9OBu6NxtYYgj9RtzHVCVQrxbGbzlI/view?usp=sharing

**Comment by mickeyseo** [comment]
Have you been repairing the glitch? Should you need more information, plz tell me. I always appreciate your support.

**Comment by iamadamdev** [comment]
Interesting, what version of FF are you on? I do not have the option to always browse in private mode under History. I'm on 60.0.2.

**Comment by mickeyseo** [comment]
61.0.1
It is currently the latest version.

**Comment by mickeyseo** [comment]
Sir. Not fixed yet? :)

**Comment by iamadamdev** [comment]
Works for me and most people, not sure why for you.

**Comment by mickeyseo** [comment]
I have just solved the problem. I have to turn off 'Tracking Protection' feature in Firefox in order to properly show HBR.org
Here is a capture video. https://youtu.be/iqMMnYlOX4I
Thank you for your help.

**Comment by iamadamdev** [comment]
Glad to hear you got it working!
