### ISSUE TITLE
TheMarker doesn't work

### ISSUE THREAD

**Issue by Moshe1942** [iamadamdev/bypass-paywalls-firefox#300]

**Comment by iamadamdev** [comment]
Which article?

**Comment by mkriaf** [comment]
@iamadamdev 
It seems that all premium articales arent working.
this is also ture to Haaertz.co.il

example:
https://www.themarker.com/markets/.premium-1.7823887

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
"Usually premium articles cannot be bypassed as they are behind a hard paywall."
