### ISSUE TITLE
Australian Financial Review no longer seems to work ?

### ISSUE THREAD

**Issue by RupertMichaelBear** [iamadamdev/bypass-paywalls-firefox#305]
was working yesterday, not today ?

**Comment by iamadamdev** [comment]
Works for me, just the annoying popup at the bottom still appears.

**Comment by flipflop11** [comment]
Hi, also nor working for me. Also have just updated to Firefox 69.0 if that's relevant

**Comment by RupertMichaelBear** [comment]
Defienetly not working for me, FF 69 W 10.

**Comment by iamadamdev** [comment]
What article?

**Comment by flipflop11** [comment]
All of them as far as I can tell. Thanks

**Comment by RupertMichaelBear** [comment]
> What article?

All of them, it blocks the bottom 2/3 of the article with an ad advising to subscribe, just like  using any other browser.

https://imgur.com/xGbGbG9

**Comment by IronicMeme** [comment]
Disabling javascript on AFR fixes it. I can get the full article but there's some javascript thing that loads up the paywall

**Comment by RupertMichaelBear** [comment]
> Disabling javascript on AFR fixes it. I can get the full article but there's some javascript thing that loads up the paywall

Thanks, I set up the blocking using Ublock Origins ability to block a site and it worked, photos aren't; showing in articles but that was as good as my workaround of redirecting them to outline.com

**Comment by IronicMeme** [comment]
> 
> Thanks, I set up the blocking using Ublock Origins ability to block a site and it worked, photos aren't; showing in articles but that was as good as my workaround of redirecting them to outline.com

Yeah, I had a quick look in the firefox debugger but I couldn't really get my head around how to step through the scripts that load on the page (and therefore which ones to block). It'd be nice to know which one controls what

**Comment by flipflop11** [comment]
> > Disabling javascript on AFR fixes it. I can get the full article but there's some javascript thing that loads up the paywall
> 
> Thanks, I set up the blocking using Ublock Origins ability to block a site and it worked, photos aren't showing in articles 

Thanks, yes the article shows but photos don't when I disable JavaScript on the uBlock Origin button. Incidentally, bypass paywall is working on Chrome for AFR website, but photos are no displaying on articles. Thanks

**Comment by iamadamdev** [comment]
Fixed in next version (disabled JS though).
