### ISSUE TITLE
The Atlantic

### ISSUE THREAD

**Issue by ashishkmrm** [iamadamdev/bypass-paywalls-firefox#306]
https://www.theatlantic.com/world/

Kindly also add this site.

**Comment by iamadamdev** [comment]
First try https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by ashishkmrm** [comment]
Working as written, kindly add the site.

**Comment by iamadamdev** [comment]
Added in the next version.
