### ISSUE TITLE
Foreign Policy is not working 

### ISSUE THREAD

**Issue by MrB010** [iamadamdev/bypass-paywalls-firefox#307]
![Screenshot_2019-09-06 Senior Officials Concede Loss of U S Clout as Trump Prepares For U N Summit](https://user-images.githubusercontent.com/47814790/64424934-19acf700-d0b3-11e9-8523-82fa6dcc2e49.png)

**Comment by iamadamdev** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/
and then refresh the page after clicking the cookie icon.
