### ISSUE TITLE
No longer works for Tech In Asia

### ISSUE THREAD

**Issue by sephwork** [iamadamdev/bypass-paywalls-firefox#308]
I tried the extension in techinasia.com, but it seems though it's not working.

**Comment by iamadamdev** [comment]
Known issue, I will remove it in the next version.

**Comment by sephwork** [comment]
Can it be fixed?

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by iamadamdev** [comment]
Added
