### ISSUE TITLE
Request for adding Costa Ricas La Nacion

### ISSUE THREAD

**Issue by ampersanded** [iamadamdev/bypass-paywalls-firefox#310]
Hi there, very nasty their paywall. Most people reading this newspaper online buying it also in paper anyways. The online edition differs in certain sections from the paper edition., which sucks because you are forced to pay 2 subscriptions. Not fair at all. La Nacion is the New York Times of Costa Rica. Link [La Nacion](https://www.nacion.com). Thanks for your consideration!

**Comment by iamadamdev** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/

**Comment by ampersanded** [comment]
Not everybody in Costa Rica knows how to disable JavaScript or use
Browser-Addons. Would be a nice move, to help people with low income. 

 

Best regards

Mit besten Grüßen 

 

 

Jan Heisterkamp

IT-Security Consultant

Ethical Hacking • Technical and Conceptual Auditing • Digital forensics •
Open Source Intelligence

Notice: Executables can be sent to us compressed with 7zip or any other
product otherwise it will be deleted.

LinkedIn:  <http://goo.gl/Lwu2Eu> http://goo.gl/Lwu2Eu • Xing:
<http://goo.gl/6cEavF> http://goo.gl/6cEavF

CONFIDENTIALITY NOTICE:

This message is intended exclusively for its addressed and may contain
confidential or privileged information. Access to this email by anyone else
is unauthorized. If you are not the intended recipient you are hereby
notified that any dissemination, copy or disclosure of this communication is
strictly prohibited by law. If this message has been received in error,
please immediately notify us via e-mail and delete it.

**Comment by iamadamdev** [comment]
I was unable to get it to work so that's why I suggested the disable JS addon.
Disabling JS on my script didn't bypass it for some reason.
