### ISSUE TITLE
Allow adding custom domains locally

### ISSUE THREAD

**Issue by wernychory** [iamadamdev/bypass-paywalls-firefox#315]
For example, I know that some local newspaper uses a paywall, which can be bypassed by removing cookies. It won't be considered by you (upstream), but I'd like to add it for me locally to automate the cookie removal.

I looked at the code, there are a couple of domain lists (remove cookies, use googlebot, etc.), so the extension could just load the user defined domains at runtime.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#sites-with-limited-number-of-free-articles

**Comment by pulmuxd** [comment]
Similar to what I wrote in #316, this is an extra mental burden to take care of the websites where I need to have the cookies removed. One needs to do it repeatedly for multiple websites and it's something that one should automate. Why not allow manually extending the list locally?

Unfortunately, one can't modify the extension without rebuilding the .xpi.

**Comment by iamadamdev** [comment]
@pulmuxd Feel free to submit a PR to add this functionality. I will happily accept.
