### ISSUE TITLE
Crains Business bypass no longer working 

### ISSUE THREAD

**Issue by djru** [iamadamdev/bypass-paywalls-firefox#317]
Paywall popup has returned.

Article I am looking at is https://www.chicagobusiness.com/crains-daily-gist/crains-daily-gist-podcast-14-million-and-just-walls-and-floor

![Crain_s_Daily_Gist_podcast__The_week_in_Chicago_residential_real_estate_and_edge_price_py_—_perfauto45](https://user-images.githubusercontent.com/7883895/64882235-554f4000-d622-11e9-8c0d-ee3cb29dc56a.png)

**Comment by iamadamdev** [comment]
Fixed in the next version.
