### ISSUE TITLE
NYtimes or other news media doesn't show its articles properly on the private window. [a captured video included]

### ISSUE THREAD

**Issue by mickeyseo** [iamadamdev/bypass-paywalls-firefox#319]
I enabled the 'Bypass paywalls' extension in the private mode, but it still doesn't work properly. I have attached the captured video. Please take a look at it and solve the glitch. Thank you.

https://drive.google.com/file/d/1DSeZnXhMjtQIiPlbwMW2eIuBbNk33dsR/view?usp=sharing

**Comment by iamadamdev** [comment]
Works fine in normal mode.
