### ISSUE TITLE
Can you please add  https://www.sacbee.com/

### ISSUE THREAD

**Issue by Crowlector** [iamadamdev/bypass-paywalls-firefox#32]
Can you please add the news site https://www.sacbee.com/?

I keep hitting a paywall.

https://account.sacbee.com/static/paywall/stop?resume=215052100#storylink=latest_side

![capture](https://user-images.githubusercontent.com/41348297/42849483-4036f09c-89d8-11e8-9b2f-333f8c98c2ab.JPG)

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed?

**Comment by iamadamdev** [comment]
Yes, then you should have no need for bypass paywalls.
