### ISSUE TITLE
Boston Globe is not available

### ISSUE THREAD

**Issue by DJRipley** [iamadamdev/bypass-paywalls-firefox#320]
Front page shows up but individual articles are blocked. Example: 

https://www.bostonglobe.com/metro/2019/09/18/new-season-same-old-story-disrespect-for-women/oUJiYec5ukZn2A7a0xrXHO/story.html

**Comment by magnolia1234** [comment]
Some 3rd party anti-adblocker script ...
I have to disable AdGuard-app and addons like Privacy Badger, uBlock Origin and uMatrix (not just disable for this website) for it to work.

**Comment by iamadamdev** [comment]
Works when disabling JS, which will be done for the next version.
