### ISSUE TITLE
Add Australian Financial Review (AFR)

### ISSUE THREAD

**Issue by kdhcap** [iamadamdev/bypass-paywalls-firefox#322]
Hi, would you consider adding the AFR? I checked the site via your steps and it looks eligible.
https://www.afr.com/

Thanks!

**Comment by nosetalgia** [comment]
My understanding is that the AFR is already included.

However, I would like to report that this extension is not working on the AFR website atm.

**Comment by iamadamdev** [comment]
Works fine for me. What article?

**Comment by iamadamdev** [comment]
Fixed in the next version (images may not load though, had to disable JS).
