### ISSUE TITLE
Add BloombergQuint

### ISSUE THREAD

**Issue by navjotjsingh** [iamadamdev/bypass-paywalls-firefox#323]
Example paywall article: https://www.bloombergquint.com/bq-blue-exclusive/jio-vs-airtel-why-airtel-could-take-on-reliance-jio-and-vodafone-idea-couldnt

Available via Google cache **(but only in text only mode)**: https://webcache.googleusercontent.com/search?q=cache:https://www.bloombergquint.com/bq-blue-exclusive/jio-vs-airtel-why-airtel-could-take-on-reliance-jio-and-vodafone-idea-couldnt&strip=1&vwsrc=0

**Comment by iamadamdev** [comment]
Original article still has paywall when disabling javascript. Let me know if you find any other workarounds.
