### ISSUE TITLE
Could you please add spectator.co.uk?

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#33]
Could you please add **spectator.co.uk/?nogeoredir=1** and **newstatesman.com**? Thank you.

**Comment by iamadamdev** [comment]
Added newstatesman.com in latest version. However I never got a paywall on spectator.co.uk after loading 10 articles. Are you sure you have uBlock Origin installed and enabled?

**Comment by defrilitus** [comment]
Thank you for responding so quickly and for adding **newstatesman.com**. With regard to **spectator.co.uk/?nogeoredir=1** there is definitely a new paywall introduced in the last week. Please see attached screengrab. Please note that the paywall has not been implemented on **spectator.us**. I don't use uBlock Origin, but rather Adblock Plus. Should I use them both? Let me know any tests I can make to help. And thanks again.
![michel barnier s pointed questions suggest no deal coffee house](https://user-images.githubusercontent.com/34283333/43053204-68815022-8df9-11e8-8d8d-c2a4daf9dc9b.png)

**Comment by iamadamdev** [comment]
Thanks for the details, it is now fixed in v1.3.6

**Comment by defrilitus** [comment]
I don't have enough words to express my appreciation ;-) Thank you.
