### ISSUE TITLE
Can this include Architectural Review?

### ISSUE THREAD

**Issue by maykef** [iamadamdev/bypass-paywalls-firefox#339]
Hi, 

I am not sure you simply can add more magazines but, it there the remotest chance you could add Architectural Review please?
https://www.architectural-review.com/

Thanks in advance

**Comment by u9bte** [comment]
Get the cookie manager add-on and delete the site cookies once the limit is reached.

**Comment by iamadamdev** [comment]
Try https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/
