### ISSUE TITLE
NYTimes Trending page completely blocked

### ISSUE THREAD

**Issue by jlhjlh** [iamadamdev/bypass-paywalls-firefox#348]
As a non-logged in user when I visit:

https://www.nytimes.com/trending/

The content area becomes completely hidden.

![image](https://user-images.githubusercontent.com/10662400/67036570-dd28de00-f0e9-11e9-8a75-f70cc0b9e5ca.png)

Using commit: `b04d7c0`

**Comment by magnolia1234** [comment]
This is not blocked by this extension, but by uBlock Origin or other AdBlocker.
