### ISSUE TITLE
It doesn't work on Caixinglobal.com

### ISSUE THREAD

**Issue by Thomasc5** [iamadamdev/bypass-paywalls-firefox#35]
Just tried the link below
Firefox prompted "An error has occurred" and the article failed to load in full

U.S. Hyperloop Developers Tap Into China
https://www.caixinglobal.com/2018-07-20/us-hyperloop-developers-tap-into-china-101306901.html

**Comment by iamadamdev** [comment]
Known issue, not all articles will work.
