### ISSUE TITLE
I can't get WSJ.com nor FT.com  with bypass paywalls!

### ISSUE THREAD

**Issue by SanFranciscoAntiGenfrifier** [iamadamdev/bypass-paywalls-firefox#355]
I have tried both Brave (Chrome) and Firefox.

I re-installed it on Chrome to no effect. Firefox would not let me re-install with a file once I deleted. 

NY Times stopped working but is working now.

Solution?

**Comment by magnolia1234** [comment]
Wsj-fix in my fork (master): https://github.com/magnolia1234/bypass-paywalls-firefox
Or wait for new release by @iamadamdev).

FT is working fine for me though.
When is the paywall active for you?

**Comment by SanFranciscoAntiGenfrifier** [comment]
NY Times and FT on Chrome. NY Times shows article, then covers it up....
Firefox works fine for these. Mysterious!

**Comment by stefanrsathianathen** [comment]
> Wsj-fix in my fork (master): https://github.com/magnolia1234/bypass-paywalls-firefox
> Or wait for new release by @iamadamdev).
> 
> FT is working fine for me though.
> When is the paywall active for you?

Have you opened a pr?

**Comment by iamadamdev** [comment]
Try now

**Comment by SanFranciscoAntiGenfrifier** [comment]
Same.

WSJ, NY Times, FT.com do not work..... Using Brave (Chrome).

Thank you.

**Comment by magnolia1234** [comment]
All works well on Chrome (no test in Brave though). My fix is incorporated in latest v1.6.0.

**Comment by SanFranciscoAntiGenfrifier** [comment]
I have to manually re-install it?

**Comment by magnolia1234** [comment]
Check for updates in addons.

**Comment by SanFranciscoAntiGenfrifier** [comment]
It does not appear to update automatically. I have 1.5.6 installed now, and
these sites appear to be working.  Thank you!

**Comment by magnolia1234** [comment]
Perfect chrome-version v1.5.6 is workong for you.
Btw I had to restart Firefox after removal old version.
