### ISSUE TITLE
NY stopped working _ 

### ISSUE THREAD

**Issue by geheime** [iamadamdev/bypass-paywalls-firefox#361]
Hi, great tool, thanks!

I wonder why it doesn´t work on ny times do. The WSJ trouble was corrected, but the ny dont. Tried turning on and off th Ublocker, cleaning cookies, etc. I have the 1.6.0. version.

The only thing that works for me it´s the bookmarklet.

Any idea on how to fix this?

Thanks!!

**Comment by iamadamdev** [comment]
Which article?
Do you have uBlock Origin installed?

**Comment by piotr-yuxuan** [comment]
Hello, thanks for this amazing extension. Here is an additional report.

- Firefox Developer Edition 71.0b3 (64-bit)
- bypass-paywalls-firefox v1.6.0
- Loaded [randon article](https://www.nytimes.com/2019/10/29/us/politics/alexander-vindman-trump-ukraine.html) from the New York Times, then navigated a couple of linked articles.
- On a computer through a tethered data connection from the European Union.

Result: it appears the article is displayed in full.

**Comment by geheime** [comment]
> 
> 
> Which article?
> Do you have uBlock Origin installed?

Yes, and tried turning on and off in the page. I repeat, in for example de WSJ it works like charm, in the NY times it doesn´t. 

Any ideas?

Thanks!

**Comment by magnolia1234** [comment]
You get the banner or what?
Use uBlock to block it.

**Comment by geheime** [comment]
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

**Comment by geheime** [comment]
> 
> 
> You get the banner or what?
> Use uBlock to block it.

Yes, I have the Ublock. Tried turning on and off and didn´t change. I get the paywall. Here are some screnshots.


![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

**Comment by magnolia1234** [comment]
No pictures though (maybe description or text on banner?).
You could try to enable more filters in the uBlock settings.

**Comment by geheime** [comment]
Sory, I can´t upload images, don´t know why. It gives me an error but doesn´t tell me what it´s the problem.

Will try with the settings.

Thanks!

**Comment by geheime** [comment]
![00](https://user-images.githubusercontent.com/57156318/68529520-5af19b00-02de-11ea-8d0e-ad928faa83d7.jpg)
![01](https://user-images.githubusercontent.com/57156318/68529521-5af19b00-02de-11ea-8e3d-65a3375b8b77.jpg)
![02](https://user-images.githubusercontent.com/57156318/68529522-5af19b00-02de-11ea-8a2c-5b5ed9e9dda5.jpg)


Here are the images! Something in my other browser must be blocking this

**Comment by magnolia1234** [comment]
You can block this by enabling uBlock with some filters.
