### ISSUE TITLE
Jeune afrique

### ISSUE THREAD

**Issue by 1Proton** [iamadamdev/bypass-paywalls-firefox#363]
Hello,

First, thank you for developping this very useful add-on. 
I would like to know if it would be possible to include the following website to the list : https://www.jeuneafrique.com/

Best regards

**Comment by magnolia1234** [comment]
Lots of articles with hard paywall.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
