### ISSUE TITLE
gramophone.co.uk

### ISSUE THREAD

**Issue by crunchypeanuts** [iamadamdev/bypass-paywalls-firefox#367]
requires subscription after viewing a few reviews, but works in private windows

**Comment by crunchypeanuts** [comment]
any progress? seems like this one should be straightforward to add and the site is very cool

**Comment by magnolia1234** [comment]
Use uBlock Origin to block paywall:
||tinypass.com^$third-party

**Comment by benp** [comment]
Sorry to ask, but where in uBlock would I put that? Thanks.

**Comment by magnolia1234** [comment]
TinyPass is blocked by default in my repo:
https://github.com/magnolia1234/bypass-paywalls-firefox-clean
