### ISSUE TITLE
NZherald.co.nz does not work

### ISSUE THREAD

**Issue by Roksteddy** [iamadamdev/bypass-paywalls-firefox#370]
Loved this add-on (till about 2 weeks ago..)

**Comment by alastairR** [comment]
They made some changes. An update has been created to fix it and hopefully should be released soon.

**Comment by peppaash** [comment]
when will this update be done

**Comment by magnolia1234** [comment]
Fixed in v1.6.1/2.

**Comment by peppaash** [comment]
not sure what that means .all I know is I download the latest version and get blank pages when trying to read where as 3-4 weeks ago the bypass was working great ,if you could tell me how to get it working again it would be much appreciated ,thanks

**Comment by magnolia1234** [comment]
Latest version should be working just fine though.

**Comment by peppaash** [comment]
just reset and its now working .thanks
