### ISSUE TITLE
Bloomberg.com

### ISSUE THREAD

**Issue by Zegna80** [iamadamdev/bypass-paywalls-firefox#373]
New paywall, can not bypass it.  Please help

**Comment by magnolia1234** [comment]
Still Working fine for me.
Which article and message?
You get 'private mode'-banner while blocking cookies though.

**Comment by Zegna80** [comment]
Works.  Thanks

**Comment by Zegna80** [comment]
Noted too

PS I did get captcha (timing issue caused by hiding banner).

**Comment by magnolia1234** [comment]
I'll add a fix in my PR for Firefox addon too.

**Comment by Zegna80** [comment]
How can i find it? Thank you

**Comment by magnolia1234** [comment]
Fixed in my PR (use my fork or wait for merge in new release if @iamadamdev ).
https://github.com/magnolia1234/bypass-paywalls-firefox

**Comment by Zegna80** [comment]
Thanks.  How can add this fix/PR?  Thank you much

**Comment by Zegna80** [comment]
Not sure how to install it.  Thank you much

**Comment by magnolia1234** [comment]
You'll have to wait for new release ...

**Comment by Zegna80** [comment]
Hi with new update, banner stays on

**Comment by magnolia1234** [comment]
Yes, @iamadamdev messed up contentScript.js with restyling (also semicolons at end of statements are removed).
Some functions are still working, but no so for Bloomberg site.

**Comment by iamadamdev** [comment]
Thanks for the heads up. I was using ESLinter, not sure how that happened. See if it is fixed in v1.6.2 now.

**Comment by magnolia1234** [comment]
Semicolons can be tricky: https://eslint.org/docs/2.0.0/rules/semi
