### ISSUE TITLE
Request -- add: The Globe and Mail [Canada]

### ISSUE THREAD

**Issue by victoriastuart** [iamadamdev/bypass-paywalls-firefox#375]
One of Canada's major papers if not the preeminent publisher.  Often paywalled; e.g.

https://www.theglobeandmail.com/business/article-nuclear-energy-is-a-vital-part-of-solving-the-climate-crisis/

https://archive.is/0bVPq

**Comment by magnolia1234** [comment]
Already added to addon, but not enabled by default in options (bug because of JavaScript disabled postfix).

**Comment by victoriastuart** [comment]
Ahhh .... enabled that news site in `Bypass Paywalls` addon, saved and reloaded G&M: works!!

Thank you!  :-)
