### ISSUE TITLE
Haaretz.co.il "highlight" block

### ISSUE THREAD

**Issue by Clegane84** [iamadamdev/bypass-paywalls-firefox#376]
Hello, first of all thanks all of you guys who are putting their time into this,

A few weeks back Haaretz.co.il started adding a "highlight" tag in the URL's of all the new articles published on the site, this change (along with some change in the interface) seems to have rendered this add-on useless for Haaretz, as 99% of all newly published content is now blocked. 

I was wondering if there's anything you can do? 

Here's an example for a link with the "highlight" tag that is being blocked, compared to a link that went up a few weeks previous to the that, doesn't have the "highlight" part, and is accessible:

https://www.haaretz.co.il/news/elections/.premium.highlight-1.8094870

https://www.haaretz.co.il/news/elections/.premium-1.8020801

I should note that simply deleting the "highlight" section from the URL used to work for a fraction of the articles, but that is no longer the case, as now all URL that have the "highlight" tag, are essentially blocked.

Thank you for the effort.

**Comment by RotterSoft** [comment]
V.1.6.0 - And Haaretz websites (Haaretz.com, Haaretz.co.il, TheMarker.com) are still blocked...

**Comment by magnolia1234** [comment]
Fixed (only) for premium articles in PR #393
