### ISSUE TITLE
Please add The Jakarta Post

### ISSUE THREAD

**Issue by bahari15** [iamadamdev/bypass-paywalls-firefox#377]
As the title suggest, The Jakarta Post is an Indonesian english-language newspaper and often wrote quality and worthwhile article to read that they lock behind a subscription paywall.

It would be really grateful if the developers would add this site, thanks.

**Comment by iamadamdev** [comment]
Did you try this first? 
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by iamadamdev** [comment]
Seems like it's behind a hard-paywall.

**Comment by bahari15** [comment]
> Seems like it's behind a hard-paywall.

Hello, sorry for the late reply, yes I have tried to access the premium articles through the firefox version of bypass paywalls to an unsuccessful result...
so apparently it's protected behind an impenetrable paywall? well that's unfortunate, thanks for trying anyways.
