### ISSUE TITLE
Sorry, but spectator.co.uk is still not working

### ISSUE THREAD

**Issue by defrilitus** [iamadamdev/bypass-paywalls-firefox#38]
Apologies, but I haven't figured out how to re-open a closed issue.
In any case, **newstatesman.com** appears to be working perfectly after installing 1.3.6.
However, the usual problems remain with **spectator.co.uk**

**Comment by defrilitus** [comment]
When someone with a track record like you gives me advice, I follow it ;-)
I'll disable the one and install the other, and give you an update tomorrow.
Thanks again.

**Comment by defrilitus** [comment]
Version 1.3.7 completely resolves spectator.co.uk, even with Adblock Plus instead of Ublock Origin ;-)
However, I will follow your advice and install the one instead of the other. Your help is much appreciated!

**Comment by defrilitus** [comment]
Apologies, but I take it back. It's not working. Try this link: https://www.spectator.co.uk/2018/07/jean-claude-drunker/

**Comment by defrilitus** [comment]
I have tried to disable Adblock Plus and substitute it with Ublock Origin, but it doesn't seem to make any difference. Possibly I am not configuring the latter as I should.

**Comment by defrilitus** [comment]
I'm attaching an example of a Spectator article that isn't working (even with uBlock Origin).
![untitled](https://user-images.githubusercontent.com/34283333/43094921-4481e248-8e82-11e8-96f9-7fd8c1e3ab2a.png)

**Comment by iamadamdev** [comment]
Some articles like that won't work. One strategy is to hit esc while it is loading and you can view the whole article (in chrome or firefox).
