### ISSUE TITLE
Washington Post popups?

### ISSUE THREAD

**Issue by sparklingwaterfall** [iamadamdev/bypass-paywalls-firefox#384]
Anyone else getting washingtonpost.com popups?

**Comment by go2tom42** [comment]
same here

**Comment by magnolia1234** [comment]
Anti-adblocker, you mean?
For now you can block javascript, but then you lose some elements like video's.

**Comment by magnolia1234** [comment]
PS disabling AdGuard also works for me (uBlock Origin is no problem).

**Comment by sparklingwaterfall** [comment]
> 
> 
> PS disabling AdGuard also works for me (uBlock Origin is no problem).

i'm confused by what you mean

**Comment by magnolia1234** [comment]
If you're getting anti-adblocker popups then disabling your adblocker (like AdGuard or uBlock Origin) should help. So what kind of popups?

**Comment by mjakebarrington** [comment]
Disabling all adblockers I had installed (ghosterly and adblock ultimate) seemed to resolve this issue on my end.

**Comment by iamadamdev** [comment]
install uBlock Origin
