### ISSUE TITLE
WSJ Pro VC

### ISSUE THREAD

**Issue by vfrazz7** [iamadamdev/bypass-paywalls-firefox#385]
Looking to access a particular article in WSJ Pro. https://www.wsj.com/articles/morgan-stanley-leading-dataminr-round-at-1-2b-pre-money-1528284601

**Comment by magnolia1234** [comment]
WSJ Pro articles have hard paywall.

**Comment by mjakebarrington** [comment]
^ Yes, WSJ Pro articles require authentication via account. The blocker works by essentially giving users unlimited preview articles, but for WSJ Pro there is no preview in the first place. Regular articles merely change client side page rendering (easy), pro articles would require penetrating the authentication system (hard, illegal).
