### ISSUE TITLE
could not download because of connection failure

### ISSUE THREAD

**Issue by tai4ji2x** [iamadamdev/bypass-paywalls-firefox#389]
why do i keep getting this error? trying to update from 1.5.1.

afraid to uninstall the old one and be unable to re-install.

tried doing it manually by downloading the zip file, but firefox says it seems to be corrupted.

**Comment by magnolia1234** [comment]
Happened to me too when trying to install addon directly from weblink. Try to first download and then install via add-ons/from file (desktop) or open with Firefox (mobile).

**Comment by tming4** [comment]
I too am having this exact problem and do not fully comprehend Magnolia's solution.I will continue playing around.

**Comment by magnolia1234** [comment]
Ah, AdGuard app (adblocker) blocked the xpi-download for me.
PS I never tried to install from zip-file.

**Comment by tai4ji2x** [comment]
is there no other way to download the xpi file? when i click "clone or download" button, it only lets me download a zip.  and then the other option given is to open in github desktop, but i tried installing that and i don't understand how it works.

**Comment by magnolia1234** [comment]
Xpi-file can be found at releases - assets.
For Firefox you have to use the signed xpi-file (actually also a zip-file).

**Comment by tming4** [comment]
I tried to download- https://github.com/iamadamdev/bypass-paywalls-firefox/releases/download/v1.6.0/bypass_paywalls-1.6.0-an+fx.xpi and I get the message that I cannot download it because of a connection failure.Disabling my ad blocker did not help.

**Comment by magnolia1234** [comment]
Try downloading with other browser.
Desktop or mobile though?

**Comment by tming4** [comment]
I managed to download it but can't open and attach it or drag it to the top of my firefox browser(MAC computer).Do I need to get rid of my 1.5.9 version first? or what.
Thanks for help.

**Comment by magnolia1234** [comment]
Search and you will find ;-)
https://fileinfo.com/extension/xpi

**Comment by tming4** [comment]
Thanks.
Very much appreciated.

**Comment by iTzJMPeezy** [comment]
Hi, I am currently having this problem and am completely lost. I cannot find a way to download any xpi files, I have only been able to download zip files. I am using Firefox desktop. Help would be greatly appreciated.

**Comment by magnolia1234** [comment]
You can't find xpi-file (releases - assets) or can't download (use other browser)?

**Comment by iTzJMPeezy** [comment]
When I try to download the xpi file it says that there is a connection failure. Do I need to use a browser other than firefox, like chrome or something?

**Comment by iTzJMPeezy** [comment]
I can find the xpi file but whenever I try to download one I get a connection failure notice. Should I try with a different browser other than firefox, like chrome or something?

**Comment by magnolia1234** [comment]
Yes, then 'install from file' in add-ons.

**Comment by iTzJMPeezy** [comment]
Actually I was able to download using chrome, and then add the file to firefox. It just took me a while to figure this out, thanks.

**Comment by magnolia1234** [comment]
Free at last ;-)
