### ISSUE TITLE
Thanks for V.1.6.2! However, it seems that most Haaretz.co.il links are still blocked...

### ISSUE THREAD

**Issue by RotterSoft** [iamadamdev/bypass-paywalls-firefox#398]
I can access the articles on the upper part of their website. However, other articles (appears lower on that same webpage) are still blocked and therefore just partly displayed. Furthermore, after few seconds - the entire page is being blocked due to use of ABP.

https://www.haaretz.co.il/gallery/television/lazy-eye/.premium.highlight-1.8155934

**Comment by magnolia1234** [comment]
Fixed in PR #395, but not yet merged in new release.
Better use uBlock Origin instead of ABP.
