### ISSUE TITLE
Can you please add support for Bloomberg as well. 

### ISSUE THREAD

**Issue by Kyahuabhai** [iamadamdev/bypass-paywalls-firefox#4]
Bloomberg just announced their new paywall, and looks the current version of the extension does not work. 

Appreciate it!

**Comment by iamadamdev** [comment]
Added!

**Comment by Kyahuabhai** [comment]
Thanks for the quick turnaround. It would be really helpful if you could also block the 30 min timer on the live tv. Appreciate the help

Regards,
Vineet Vaishnav

Sent from my iPhone
________________________________
