### ISSUE TITLE
WSJ formatting issue

### ISSUE THREAD

**Issue by 7LRX** [iamadamdev/bypass-paywalls-firefox#401]
About 6-10 weeks ago, I started having formatting issues on WSJ (Firefox/Android).  The site initially loads an almost-desktop-looking version of the home page, with stories arranged into three or four columns, before finally producing the expected single-column "mobile" view of the page.  This process can take up to 20 seconds, during which time the phone struggles to do simple things like scrolling down the page.

Okay, perhaps my phone has issues, so I tried it on desktop.  Same problem: if Firefox is not full-screen, then the WSJ home-page initally loads in four-column mode (with the last column half-off the screen) before reformatting into a three-column mode that fits the current window size.  Much quicker than Android of course, but still about 5 additional seconds to finish reformatting.

Troubleshooting: disabled all other extensions, clear cache/cookies, checked for updates, etc.  

The problem goes away by simply unchecking WSJ in the BP options menu.

**Comment by magnolia1234** [comment]
Since a month BP add-on sets useragent to Googlebot to bypass the WSJ paywall, but there is also a mobile version.
This happens only first time during session though.

**Comment by 7LRX** [comment]
Not sure what exactly you meant by "This happens only first time during session though."

The reformatting issue occurs everywhere, every time: select an article to read, reformat.  Press "back" and reformat. Navigate between sections (like from "World" to "Tech", and get the reformat.

The constant reformatting has made the site worthless on Android/Firefox; and just plain irritating on Windows/Firefox.
