### ISSUE TITLE
New York Times Constantly Refreshing

### ISSUE THREAD

**Issue by kwehner** [iamadamdev/bypass-paywalls-firefox#402]
With Bypass Paywalls enabled for the New York Times website, it's constantly refreshing. I wonder if NYT changed something as I just noticed this issue for the first time this morning.

**Comment by magnolia1234** [comment]
No refreshing here, but slow at loading video-elements.

**Comment by judy** [comment]
Yup, I'm seeing this now, on a number of pages. Just now it was [this link](https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html). I disabled the extension and the behavior went away, so it's definitely this plugin.

**Comment by iamadamdev** [comment]
That article works fine for me, do you have uBlock Origin installed?

**Comment by judy** [comment]
I have Nano Adblocker and Nano Defender installed. To rule them out, I enabled Bypass Paywalls and disabled both Nano extensions, then restarted firefox. The problem persists.

To be more clear, the page finishes loading all assets, then goes idle for roughly half a second. Then it acts like someone is hitting the refresh button on the page. And repeats.

**Comment by iamadamdev** [comment]
do you have uBlock Origin installed?

**Comment by iamadamdev** [comment]
Goto that link and start scrolling down, it worked for me w/o refreshing. I had uBlock Origin also installed and enabled.

**Comment by Archibaldie** [comment]
Hi, I am actually experiencing the same issue. Nytimes.com will constantly refresh (on any page) when Bypass Paywalls is active. 

I only have uBlock Origin and Facebook Container add-ons installed. Disabling these add-ons does not resolve the issue. However, disabling Bypass Paywalls does.

**Comment by Archibaldie** [comment]
It seems that disabling Bypass Paywalls on NYT and using only uBlock Origin allows me to get through the paywall.
