### ISSUE TITLE
Please add Stratfor

### ISSUE THREAD

**Issue by hedonia** [iamadamdev/bypass-paywalls-firefox#403]
https://worldview.stratfor.com/article/france-gets-its-chance-lead-europe-macron-merkel-eu-brexit?_hsenc=p2ANqtz-_UwL80L1n2QfHCUKvsi8H10lyFUhyyj3mv6M3thi6gyhvtXe_vTvvUic8E3rG7ukj-ThwkucBYtq0sW3SJhif43bxL3w&_hsmi=80262103

**Comment by magnolia1234** [comment]
Hard paywall (subscription).
