### ISSUE TITLE
Please add the following media

### ISSUE THREAD

**Issue by qnoum** [iamadamdev/bypass-paywalls-firefox#404]
Please add the following media if possible

   french:
lefigaro.fr
mediapart.fr
monde-diplomatique.fr
courrierinternational.com
nouvelobs.com
liberation.fr
lejdd.fr
lopinion.fr
lesoir.be
letemps.ch

   german:
zeit.de
welt.de
sueddeutsche.de
faz.net
diepresse.com

   us and uk:
harpers.org
the-tls.co.uk
nybooks.com
chronicle.com
bostonglobe.com

Thank you!

**Comment by magnolia1234** [comment]
Did you try
https://github.com/iamadamdev/bypass-paywalls-chrome#sites-with-limited-number-of-free-articles
and
https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests
?
PS some sites already in list (Firefox or Chrome).

**Comment by qnoum** [comment]
Sorry I didn't pay enough attention to this. 
These are all large major media websites. 
It seems only lejdd.fr and lopinion.fr qualify for the conditions though,
while harpers and the-tls.co.uk can be bypassed by clearing cookies.
The rest of it looks like a hard paywall unfortunately.

bostonglobe is included because while it already works 
it still doesn't show pictures well for some reason.
letemps.ch is already in the list but it doesn't work by me at all 
and also looks like a hard paywall.

**Comment by magnolia1234** [comment]
A few sites (Harpers/Die Zeit) can still be added from the Chrome extension, but letemps.ch and liberation.fr are not working (anymore?) for premium-articles.
The Boston Globe needs Javascript to be blocked which causes the pictures not to be loaded.

**Comment by qnoum** [comment]
Can the Chrome extension really open Die Zeit Plus articles? 
For me they seem totally hard paywalled.
If it works then why is such difference with Firefox?

**Comment by magnolia1234** [comment]
BP (Chrome) is also not working for Die Zeit plus-articles (just no limit for regular articles).

**Comment by magnolia1234** [comment]
New fix for Boston Globe (only block paywall-script).
Still uBlock Origin (cosmetic filters) can block images.

**Comment by qnoum** [comment]
Reinstalled it and The Boston Globe images are still blocked even when I disable uBlock Origin completely.

**Comment by magnolia1234** [comment]
Boston Globe is still working fine here (even with Adguard & uBlock Origin on Android).
Maybe disable site in options, refresh page and enable again (some cookies only set by blocked paywall-script).
