### ISSUE TITLE
economist mobile revised version not working

### ISSUE THREAD

**Issue by dragonhailstone** [iamadamdev/bypass-paywalls-firefox#405]

**Comment by magnolia1234** [comment]
Revised version in my PR is working just fine. Are you using all changed files though (including manifest.json)?

**Comment by dragonhailstone** [comment]
Yes. Used your recent PR and not working..

**Comment by magnolia1234** [comment]
You made an unsigned xpi-file of my fork?
And did you re-enable Economist in optione (title changed)?

**Comment by dragonhailstone** [comment]
Yes. Used most recent unsigned fork of yours which was modified 14hours ago and enabled renamed _Economist_ option which was _Economist(javascript disabled)_ before.

**Comment by magnolia1234** [comment]
Some weird timing issue on Android, but refreshing the page fixes the issue for now though.
