### ISSUE TITLE
ET Prime

### ISSUE THREAD

**Issue by u9bte** [iamadamdev/bypass-paywalls-firefox#406]
Website: `https://prime.economictimes.indiatimes.com`

Changing the user agent to Google bot removes paywall. Please include in the next update.

**Comment by iamadamdev** [comment]
Please submit a PR for this and I will include it

**Comment by magnolia1234** [comment]
Still needs update to manifest.json to work.

**Comment by iamadamdev** [comment]
Added

**Comment by magnolia1234** [comment]
Still not working though (just intro).
Any actual positive test?

**Comment by u9bte** [comment]
It doesn't work on the homepage, buy works on the individual articles once you navigate to them.

**Comment by magnolia1234** [comment]
Googlebot as user-agent works, but until my fix not in the BP add-on.

**Comment by u9bte** [comment]
Is there a way to change useragent on the homepage alone? Would be much better. TIA

**Comment by magnolia1234** [comment]
You mean the other way around (BP only active for articles), I guess?
Googlebot indeed gives a blank homepage and messes up the recommendations at bottom article (last can't be fixed though).
