### ISSUE TITLE
Request for firewall bypass: NK News

### ISSUE THREAD

**Issue by loganansell** [iamadamdev/bypass-paywalls-firefox#407]
Hey, I'm a news junkie and absolutely LOVE your program.  I wanted to request that NK News (nknews.org) be added to your list of supported sites. It's the top site for North Korean news, which might sound niche, but it has a very large readership.  I tested and articles are available if searched from Google in incognito mode, so it should be possible to bypass the paywall.

Warm thanks,

Logan

**Comment by iamadamdev** [comment]
Added for the next release.
