### ISSUE TITLE
corriere.it paywall not bypassed

### ISSUE THREAD

**Issue by RNiK** [iamadamdev/bypass-paywalls-firefox#41]
As you can see in the attached image, corriere.it paywall is not bypassed.
I'm using version 1.3.7 with Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0.

https://screenshots.firefox.com/yNq7oDLqBgZ01T7k/corrieredibologna.corriere.it

**Comment by iamadamdev** [comment]
Might not work for all articles. Shall I remove it from the list?
