### ISSUE TITLE
New website request.

### ISSUE THREAD

**Issue by MattRGX** [iamadamdev/bypass-paywalls-firefox#412]
Hello,
thanks for your amazing work.

Can you add these 2 big french websites to the list ?

https://www.sudouest.fr/

(exemple of premium article : [https://www.sudouest.fr/2019/12/10/ils-ont-vraiment-tente-de-me-tuer-6938433-10142.php](url) )

https://www.ouest-france.fr/

(exemple of premium article : [https://www.ouest-france.fr/environnement/pollution/entretien-il-y-20-ans-le-naufrage-de-l-erika-quels-risques-de-pollutions-en-mer-aujourd-hui-6647311](url) )

Thanks a lot for your help !

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by MattRGX** [comment]
Hello,

Thanks for your answer but i don't understand it ! 
Can you explain me where is the problem with my request to understand why it's bad ? Like that i won't do the mistake again !

Thanks a lot

**Comment by iamadamdev** [comment]
Did you try bypassing it with the method described? Does it remove the paywall? Also those aren't exactly major newspapers.

**Comment by MattRGX** [comment]
Ok thanks for your answer. 
Sorry but in france those are major website. 

For the method describes, i saw some other website already supported by your extension that are not working in private mode. I told myself that you could do the same with those one ! 
Lemonde for example is not working in private mode. Still the paywall !
But it works with your extension !

**Comment by MattRGX** [comment]
Hello, 
It's me again, sorry but i just want to understand the way it works for website request.
I saw in the last release that you added "Le Parisien" (which is local newspaper exactly like the 2 sites i asked for and even smaller).

I tried bypassing "Le Parisien" with the method described but it didn't work. In private mode (with your extension disabled) it didn't work at all. I still have the paywall.

So i don't get the difference with "Le Parisien" and the two websites i asked for.

If you can explain me it would be great.

Thanks a lot for your help

Regards,

**Comment by magnolia1234** [comment]
SudOuest.fr has hard paywall (only subscription).
Ouest-France.fr has repeating reCaptcha because of supposed Javascript-block (for me) ...
PS there are a lot of different types of paywalls.

**Comment by MattRGX** [comment]
Ok thanks it's another kind of paywall ! 
But for me, as a simple web-user, a paywall is a paywall. The article is only for subscribers, no matter the type of paywall. 
How can we make difference between different type of paywalls ? i don't want to do the mistake again !

**Comment by magnolia1234** [comment]
Check the options in new request list to disable paywall.
Or you can change user-agent to Googlebot or disable javascript (with other extensions).
So far it's trial and error or you have to look into the html-code of the website (for soft paywall).

**Comment by magnolia1234** [comment]
Ouest-France.fr also has a hard paywall (block because of using Googlebot as user-agent).

**Comment by MattRGX** [comment]
> 
> 
> Check the options in new request list to disable paywall.
> Or you can change user-agent to Googlebot or disable javascript (with other extensions).
> So far it's trial and error or you have to look into the html-code of the website (for soft paywall).

Yes i checked it ! But for example, with Le Parisien, the method did'nt work ! Still the paywall even in private mode ! That's why i don't get the difference between Le parisien and the websites i asked for ! 
Even with another website "Le Monde" which is available in the extension, the new request method doesn't work at all ! 
So it's not possible to see the difference !

**Comment by magnolia1234** [comment]
As I said before, both your sites have a hard paywall (no fix by BP) ...

**Comment by MattRGX** [comment]
Yeah i got it ! But as i said before i don't know how to make difference between hard paywall and soft ones ! So it's possible for me to do another mistake when i will ask for new request !

**Comment by magnolia1234** [comment]
Relax, the checklist is only for sites with a free article limit.
Adam's default answer invites you to check for this, but BP can also use some extra anti-paywall measures (like using Googlebot, block Javascript or unhide article content).

**Comment by MattRGX** [comment]
I'm relax :) 
Ok so it works only with websites that have a free article limit ?

**Comment by magnolia1234** [comment]
Read well first: there are more options than a fix by incognito mode + google search (in checklist).
