### ISSUE TITLE
NY Times now asking for login (Chrome)

### ISSUE THREAD

**Issue by SanFranciscoAntiGenfrifier** [iamadamdev/bypass-paywalls-firefox#414]
Not having this problem with Firefox!

"Keep reading the Times" popup obscures text!

example:

https://www.nytimes.com/2019/12/12/us/impeachment-democrats-republicans.html?action=click&module=Top%20Stories&pgtype=Homepage

**Comment by magnolia1234** [comment]
No popup for me though.
Could you include a screenshot?

**Comment by SanFranciscoAntiGenfrifier** [comment]
The popup is still at the bottom, but it does not expand anymore  —  thank
goodness!

Is there a way to add a screenshot to posts here?

**Comment by magnolia1234** [comment]
You can add a image to your comment here (3rd icon from the right). How to make a screenshot depends on your device.

**Comment by magnolia1234** [comment]
Banner 'Access more for free' can be blocked by adblocker like uBlock Origin though.
