### ISSUE TITLE
Fixed in PR #395, but not yet merged in new release.

### ISSUE THREAD

**Issue by RotterSoft** [iamadamdev/bypass-paywalls-firefox#417]
Thank you for efforts. Unfortunately - the problem has yet to be solved in v.1.6.3: 
Though Haaretz.com seems to be accessible (thank you!!) - Haaretz.co.il and TheMarker.co.il - are still blocked (after few seconds) with paywalls. 

Fixed in PR #395, but not yet merged in new release.
Better use uBlock Origin instead of ABP.

_Originally posted by @magnolia1234 in https://github.com/iamadamdev/bypass-paywalls-firefox/issues/398#issuecomment-557919870_

**Comment by magnolia1234** [comment]
TheMarker has a anti-adblocker script (hblock), you mean?
Haaretz.co.il is working just fine for me (with or without uBlock Origin).

**Comment by RotterSoft** [comment]
Yep, you right - now TheMarker works fine.
However, Haaretz.co.il still urging me to turn off ABP, which is my preffered adblocker: 
Main page displays fine. But once I'm trying to access an article - I have just 2secs to read it, before it is being covered with a message asking me to turn off ABP. After turning it off - I do have access to the articles but it contains too many annoying ads (which cannot be blocked when ABP is off).

**Comment by iamadamdev** [comment]
ABP is garbage, use uBlock Origin, here is why:
https://github.com/gorhill/uBlock/wiki/uBlock-vs.-ABP:-efficiency-compared

**Comment by magnolia1234** [comment]
Also no anti-adblocker screen or ads with uBlock Origin and all filterlists active.
BP can't block script without losing menu and images of recommendations etc.
