### ISSUE TITLE
Risk.net

### ISSUE THREAD

**Issue by mushkhach** [iamadamdev/bypass-paywalls-firefox#418]
It will be great to see risk.net in the list of paywall bypass. Thank you

**Comment by iamadamdev** [comment]
Only large or major sites will be considered. No small sites or local newspapers.
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests

**Comment by mushkhach** [comment]
It is the world's largest risk management content maker with subscription fee above 3000$. Anyway thank you for great work

**Comment by magnolia1234** [comment]
Hard paywall though.
