### ISSUE TITLE
Sacramento Bee

### ISSUE THREAD

**Issue by agiacalone** [iamadamdev/bypass-paywalls-firefox#427]
Can you please add the Sacramento Bee to the list? The paper has a view limit and it works if I use it in private browsing (no cookies) with the Google result. The link that got me to hit the paywall limit is listed below, but it will probably work with most articles.

https://www.sacbee.com/food-drink/restaurants/article238788888.html

**Comment by magichandthing** [comment]
Use [Cookie Remover](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/) to reset the limit.
