### ISSUE TITLE
Bloomberg Quint is not working. 

### ISSUE THREAD

**Issue by jain202** [iamadamdev/bypass-paywalls-firefox#429]
Bloomberg Quint is not working.  it block the access.

**Comment by magnolia1234** [comment]
BQ Blue Exclusive articles have hard paywall, it seems.

**Comment by magnolia1234** [comment]
BP was not working at all on Bloomberg Quint ...
See PR #423

**Comment by iamadamdev** [comment]
Only works on free articles, not premium ones.
