### ISSUE TITLE
doesn't work with vanity fair

### ISSUE THREAD

**Issue by yayagal251** [iamadamdev/bypass-paywalls-firefox#43]
Tried it today.  Doesn't work.

**Comment by iamadamdev** [comment]
Still works fine for me. Do you have uBlock Origin installed? Tried clearing vanityfair cookies?

**Comment by tlc** [comment]
![vf](https://user-images.githubusercontent.com/19436/53197502-608c4100-35e8-11e9-9959-0cc2d8a6bb40.png)

Cleared the cookies and have uBlock Origin

**Comment by tlc** [comment]
FYI,
A VF link on reddit had '#~o' appended.  The URL was triggering a paywall until I removed that.
