### ISSUE TITLE
Requesting to bypass https://www.theinformation.com

### ISSUE THREAD

**Issue by Shriyanshagro** [iamadamdev/bypass-paywalls-firefox#437]

**Comment by magnolia1234** [comment]
Site seems to have a hard paywall.

**Comment by Shriyanshagro** [comment]
is there any way around to it?

**Comment by magnolia1234** [comment]
Not likely.

**Comment by Shriyanshagro** [comment]
Thanks for looking into it. Closing it now.
But let me know, if you come across a way through it anytime.
