### ISSUE TITLE
Not working on nytimes.com

### ISSUE THREAD

**Issue by StephenAtty** [iamadamdev/bypass-paywalls-firefox#44]
Unchecked it and re-checked it. Still doesn't work

**Comment by iamadamdev** [comment]
do you have ublock origin installed?

**Comment by StephenAtty** [comment]
No I don't

**Comment by iamadamdev** [comment]
Mine stays at "You have 4 free articles remaining." on everything I click on. What article isn't working for you? Try manually removing nytimes.com cookies.

**Comment by StephenAtty** [comment]
I didn't get the notification of your previous comment. I cleared all the cookies and it gives me 4 free articles - counting down after each one. It doesn't matter which articles I read.
