### ISSUE TITLE
Paywall Free for The Strait Times 

### ISSUE THREAD

**Issue by kchio0331** [iamadamdev/bypass-paywalls-firefox#440]
Hi, 

Can you please try to have three Singapore's newspapers to be paywall free? 

1) The Strait Times at https://www.straitstimes.com/global
2) The Business Times at https://www.businesstimes.com.sg/
3) Lianhe Zhaobao at https://www.zaobao.com.sg/

They aim to global audience in my opinion. Please let me know what you think. 

Thank you.

**Comment by magnolia1234** [comment]
First two sites have premium articles with a hard paywall (subscription only).
