### ISSUE TITLE
Saving articles to pocket

### ISSUE THREAD

**Issue by aki-sud** [iamadamdev/bypass-paywalls-firefox#441]
Please provide a way to save paywall broken articles from sites such as ft(https://www.ft.com/) to pocket

**Comment by magnolia1234** [comment]
With Pocket you share a weblink, not the complete text. Maybe possible with a future version of Push to Kindle though.

**Comment by magichandthing** [comment]
This is possible with Instapaper if you save articles with the Instapaper extension. Not sure about Pocket.

**Comment by magnolia1234** [comment]
That's the issue, but Instapaper won't work either (without a subscription).

**Comment by magichandthing** [comment]
The Instapaper extension does more than just pass a weblink to Instapaper for saving… it parses the content as well.

Have a look here: https://addons.mozilla.org/firefox/downloads/file/1591218/instapaper-1.0.5-fx.xpi?src=dp-btn-primary @ bookmarklet.js

or verify by saving to Instapaper an article on any site that works with bypass paywalls. It works with Instapaper.

**Comment by magnolia1234** [comment]
Not with Instapaper app though and addon is stuck at saving ...
PS BP-addon not working on FT anymore, it seems.

**Comment by magnolia1234** [comment]
FT not working (only) at Firefox Android version.

**Comment by magnolia1234** [comment]
Indeed, Instapaper saves the complete article (instead of Pocket).
I hadn't used it in a long time ;-)
