### ISSUE TITLE
The Economist articles no longer working

### ISSUE THREAD

**Issue by dwb3450** [iamadamdev/bypass-paywalls-firefox#442]
articles from The Economist no longer working.... pages seem to be stuck in a loop...  probably something to do with their new website...

https://www.economist.com/technology-quarterly/2020/01/02/china-has-never-mastered-internal-combustion-engines

**Comment by Yu4n** [comment]
TE has updated a new layout:(

**Comment by vtruong68** [comment]
Same issue. There appears to be an infinite loop of page reloading.

**Comment by magnolia1234** [comment]
Fixed in https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by dwb3450** [comment]
Fixed.  Nice job!
