### ISSUE TITLE
Globe and mail - no longer works

### ISSUE THREAD

**Issue by kicksturns** [iamadamdev/bypass-paywalls-firefox#444]
The globe and mail paywall was updated today and articles are no longer accessible.

**Comment by magnolia1234** [comment]
Fixed in my PR #423, but not yet merged.
You could make a unsigned xpi-file from my fork though.

**Comment by kicksturns** [comment]
Ok thanks for the update!

**Comment by rfc1739** [comment]
Thank you!  Looking forward to it!

**Comment by magnolia1234** [comment]
https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by llacb47** [comment]
Test in uBlock Origin: `theglobeandmail.com##+js(set, keytar.accessAllowed, true)`

**Comment by iamadamdev** [comment]
Fixed in latest version.
