### ISSUE TITLE
Latest version doesn't have the The Athletic 

### ISSUE THREAD

**Issue by afk789** [iamadamdev/bypass-paywalls-firefox#445]
I downloaded the latest version of bypass-paywalls for Firefox but it doesn't contain The Athletic.

**Comment by magnolia1234** [comment]
Request or complaint? ;-)

**Comment by afk789** [comment]
Complaint

**Comment by magnolia1234** [comment]
PR #423

**Comment by magnolia1234** [comment]
Fixed in https://github.com/magnolia1234/bypass-paywalls-firefox-clean
