### ISSUE TITLE
Request please - https://www.heraldsun.com.au/

### ISSUE THREAD

**Issue by BillTrovalds** [iamadamdev/bypass-paywalls-firefox#447]
Can we please get https://www.heraldsun.com.au/ added?

Great work.

Much appreciated.

Thank you.

**Comment by BillTrovalds** [comment]
Thank you @iamadamdev much appreciated.

I'm no pro programmer but how can I help with this?

**Comment by BillTrovalds** [comment]
Whoops, I thought it has been added. My mistake, sorry.

**Comment by iamadamdev** [comment]
https://github.com/iamadamdev/bypass-paywalls-firefox#new-site-requests
