### ISSUE TITLE
Breaks NYTimes login for subscribers

### ISSUE THREAD

**Issue by NelsonMinar** [iamadamdev/bypass-paywalls-firefox#448]
Thank you so much for this addon. I use it for the 50+ sites that I can't bother to pay to access.

However, I do pay for the NYTimes. But with this addon active I can't log in to my NYTimes subscription. I complete the username, password, and CAPTCHA and then the NYTimes site redirects me to an offer to pay to subscribe and the site acts like I'm still not logged in. It works as soon as I disable Bypass Firewalls.

Not sure what the general solution here is, it may be an impossible problem. Feel free to close this if you don't want to bother with this kind of problem.

**Comment by qnoum** [comment]
I have similar problem with Quora. I don't pay for it, but have an account, and it breaks my attempts to login even though I opted out Quora in Bypass options.
