### ISSUE TITLE
Add request for lastampa.it/topnews

### ISSUE THREAD

**Issue by gioxx** [iamadamdev/bypass-paywalls-firefox#450]
Good morning and thanks for your work. Can you please consider to add laStampa.it to unlock list? It's a large italian newspaper read on all over the country.

This is an example article blocked by paywall: https://www.lastampa.it/topnews/edizioni-locali/torino/2020/01/14/news/sanita-sistemi-informatici-in-tilt-si-torna-alle-vecchie-ricette-tradizionali-1.38327206

At this moment I use a Greamonkey script to unblock it, you can find that script here: https://greasyfork.org/it/scripts/371681-la-stampa-topnews-full-text-articles

Thanks.

**Comment by magnolia1234** [comment]
Added in https://github.com/magnolia1234/bypass-paywalls-chrome-clean

**Comment by iamadamdev** [comment]
Added
