### ISSUE TITLE
More requests please - a few Australian based sites

### ISSUE THREAD

**Issue by BillTrovalds** [iamadamdev/bypass-paywalls-firefox#452]
Can we please have the following added:

- https://www.adelaidenow.com.au/
- https://www.themercury.com.au/
- https://www.ntnews.com.au/
- https://www.perthnow.com.au/
- https://www.brisbanetimes.com.au/
- https://www.cairnspost.com.au/
- https://www.townsvillebulletin.com.au/
- https://www.goldcoastbulletin.com.au/
- https://www.newcastleherald.com.au/
- https://www.illawarramercury.com.au/
- https://www.batemansbaypost.com.au/

Thank you

**Comment by iamadamdev** [comment]
"Only large or major sites will be considered. No small sites or local newspapers."
