### ISSUE TITLE
The Economist

### ISSUE THREAD

**Issue by joamgias88** [iamadamdev/bypass-paywalls-firefox#454]
Hey, for some reason it seems like the above websites fails to load articles with the add-on installed

**Comment by u9bte** [comment]
Same here. Archive's crawler is able to access it. Google webcache seems to be having problems.

**Comment by aensaro** [comment]
For me it keeps reloading and reloading and reloading the page but the content is still truncated after the first 2 paragraphs or so.
Also! Not complaining, I tried on another site I like and it works, really cool project!

**Comment by magnolia1234** [comment]
Fixed in https://github.com/magnolia1234/bypass-paywalls-chrome-clean
