### ISSUE TITLE
Please add The Independent Premium

### ISSUE THREAD

**Issue by jp-coetzee** [iamadamdev/bypass-paywalls-firefox#455]
Some of the page loads in Google's cache, which it does not when viewed directly..? So I guess it can be added to the extension?

many thanks
Direct link: https://www.independent.co.uk/independentpremium/long-reads/war-drugs-cocaine-amphetamines-opioids-a9276396.html

Google cache: https://webcache.googleusercontent.com/search?q=cache:rkq3lK7YfAoJ:https://www.independent.co.uk/independentpremium/long-reads/war-drugs-cocaine-amphetamines-opioids-a9276396.html+&cd=1&hl=en&ct=clnk&gl=uk&client=firefox-b-d

**Comment by magnolia1234** [comment]
A bit short article for a long-read (also in Google cache) ...

**Comment by jp-coetzee** [comment]
Yeah. But that short article is different from the non-cached page..?

**Comment by magnolia1234** [comment]
No, both are short (just hidden paywall-banner).
So Google Cache is not a fix.
