### ISSUE TITLE
New Request

### ISSUE THREAD

**Issue by kchio0331** [iamadamdev/bypass-paywalls-firefox#457]
Hello,

Can you please make the following websites paywall free? 

1) Sacramento Bee of California at https://www.sacbee.com/
2) The American Interest at https://www.the-american-interest.com/
3) I clicked on an English article from Caixin at https://www.caixinglobal.com/2020-01-18/central-bank-official-dashes-hope-for-deposit-rate-reform-101505750.html, but it is not paywall free. Can you please fix the issue to ensure all articles are paywall free? 
Moreover, Caixin has a Chinese website. Can you please make both the English and Chinese websites of Caixin paywall free? 
4) Chronicle of Higher Education at https://www.chronicle.com/
5) Do you think you can make a Taiwan's database paywall free? The website is https://www.airitilibrary.com/Search/alJnlbrowse

Thank you!

**Comment by iamadamdev** [comment]
Some articles on caixin are behind a hard paywall.
