### ISSUE TITLE
Sun Sentinel Not Working

### ISSUE THREAD

**Issue by bobking69** [iamadamdev/bypass-paywalls-firefox#464]
Bypass Paywalls not working on Sun Sentinel on Firefox. 
Also, tried cookie remover and Private window and they don't work.

Please also consider adding Miami Herald to list. Tried cookie remover and Private window and they don't work on this paper.

Thanks.

**Comment by iamadamdev** [comment]
Just loaded 10+ articles fine on sun-sentinel.com.
Do you have uBlock Origin installed?
