### ISSUE TITLE
Release download error -- connection failure

### ISSUE THREAD

**Issue by Haroldoa** [iamadamdev/bypass-paywalls-firefox#466]
![error](https://user-images.githubusercontent.com/23324718/73032052-c84b9d00-3df2-11ea-9eb5-bbfba4745fda.PNG)

Clicking on the release link does not work to install

To install the addon right now 
1.you can download
https://github.com/iamadamdev/bypass-paywalls-firefox/files/2609079/iamadamdev.hotmail.com.xpi.txt
2. save as iamadamdev.hotmail.com.xpi (take out the .txt extension to save as .xpi)
3. drag the file into firefox
4.install works

**Comment by iamadamdev** [comment]
thanks
