### ISSUE TITLE
La Repubblica issues

### ISSUE THREAD

**Issue by ciru86** [iamadamdev/bypass-paywalls-firefox#468]
Hi, if I visit the articles on rep.repubblica.it using bypass-paywalls-firefox on desktop everything's all right, while if I try to visit it with firefox on android the page keeps reloading and never shows content. I tried Android Firefox and Firefox nightly, and I've tried to install bypass paywall 1.6.3 and the clean versione 1.6.3.6.
Could you help?
Thank you!!

**Comment by iamadamdev** [comment]
Try the latest version.

**Comment by joker327** [comment]
> Try the latest version.

'Fix' not working, did you test it yourself though?
