### ISSUE TITLE
caixin chinese not working

### ISSUE THREAD

**Issue by ddgg** [iamadamdev/bypass-paywalls-firefox#473]
caixin chinese can't bypass paywall, still redirect to subscription page after log into free account and click "本文共计nnn字订阅后继续阅读“
english version is working, thank you for this great extension

**Comment by iamadamdev** [comment]
What's the url for the Chinese site?

**Comment by ddgg** [comment]
this is the page of weekly magazine,
http://weekly.caixin.com/
 click any cover will list all the articles like this one:
http://weekly.caixin.com/2020-01-18/101505541.html
also from english landing page of caixin.com, in the up right corner  there's a link display '中文' , which will lead to chinese index page.
thank you

**Comment by iamadamdev** [comment]
Unfortunately some articles there are behind a hard paywall.
