### ISSUE TITLE
https://the-ken.com/

### ISSUE THREAD

**Issue by aki-sud** [iamadamdev/bypass-paywalls-firefox#474]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. For small sites try the [Cookie Remover](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/) Add-on to remove cookies (might not work though).

1. Visit an article on the site you want to bypass the paywall for and copy the article title.
2. Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
3. Click on the same article from the Google search results page. If it loads without a paywall you can submit a request here, otherwise my extension cannot bypass it either.

Usually premium articles cannot be bypassed as they are behind a hard paywall.

**Comment by iamadamdev** [comment]
Did steps 1-3 work?

**Comment by kapilkchaurasia** [comment]
Seems like they are behind hard paywall.

**Comment by aki-sud** [comment]
YES
