### ISSUE TITLE
London Review of Books gets stuck in a loading loop

### ISSUE THREAD

**Issue by cosumus** [iamadamdev/bypass-paywalls-firefox#475]
when going to lrb.co.uk
it redirects to this repeatedly 
https://lrb.co.uk/session?redirect=https%3A%2F%2Flrb.co.uk%2F&sessions_to_set=%7B%22paywall%22%3A%7B%22subscribed%22%3Afalse%2C%22type%22%3Anull%2C%22expires%22%3Anull%2C%22article_access%22%3A%22hide%22%2C%22sub_system%22%3Anull%2C%22logged_in%22%3Afalse%7D%2C%22institution_ip%22%3A%22< IP ADDRESS >%2C+<IP ADDRESS>%22%7D

**Comment by cosumus** [comment]
n.b. disabling lrb.co.uk on the addons drop down menu does not seem to resolve this problem, but disabling allows the site to load.

**Comment by iamadamdev** [comment]
Will be fixed in next release, for now the Chrome version is fixed since you don't need to wait for version updates there.

**Comment by iamadamdev** [comment]
Fixed
