### ISSUE TITLE
New site request: La Stampa

### ISSUE THREAD

**Issue by Thalon77** [iamadamdev/bypass-paywalls-firefox#478]
Just asking to add a certain italian newspaper's site called "La Stampa" to the list.
Seems the paywall is not so difficult to circumvent considering that the whole text of the article can be read in the page source under div class="entry__content" id="article-body".
Here's [an article page](https://www.lastampa.it/topnews/primo-piano/2020/01/29/news/taverna-candidata-anti-di-maio-una-fedelissima-gestira-crimi-1.38394822) for reference and research.

**Comment by gabrythe23** [comment]
I've checked the div just a couple of minutes ago and into it, there's just the article summary not the whole text

**Comment by Thalon77** [comment]
I see both the text that I can see as preview and also some more covered by the the fading effect and the "register to see" prompt.
Easy to find using firefox to see the page source considering it's one of the longest lines displayed onscreen (line 1073), everything after the second "span" tag is hidden text.

**Comment by messi485** [comment]
Other repo: https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by kingkong914** [comment]
Check https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by iamadamdev** [comment]
Added in latest version!

**Comment by joker327** [comment]
Nice, but how do you know which Javascript-code to block?

**Comment by Thalon77** [comment]
Thanks!

**Comment by spoetnik412** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-firefox-clean
