### ISSUE TITLE
No more updates to Firefox addon?

### ISSUE THREAD

**Issue by joker327** [iamadamdev/bypass-paywalls-firefox#480]
How come there are so few updates to the Firefox addon compared to the Chrome extension?
For mobile I prefer Firefox over adware Yandex.

**Comment by Thalon77** [comment]
The guys at Mozilla Foundation think that this extension violates their guidelines (or better, they recieved some pressions from the owner of the sites that have paywalls bypassed by this extension).
It's very difficult to develop an extension for a browser if the developer of that browser is against you.

**Comment by joker327** [comment]
Firefox still signs this addon, so that's not the issue here.
Just less updates and no new sites like La Stampa.

**Comment by iamadamdev** [comment]
There are, just takes more work to do a FF release.
You can also use the Chrome version here: https://github.com/iamadamdev/bypass-paywalls-chrome

**Comment by joker327** [comment]
No option for Android though (no Chrome extensions).
Btw you can sign an Firefox add-on in less than 5 minutes.

**Comment by iamadamdev** [comment]
It's not instant anymore, last time it took 10 minutes before I could download the signed version.

**Comment by iamadamdev** [comment]
btw does auto-update of the extension work for you on mobile (firefox on android)?

**Comment by joker327** [comment]
> It's not instant anymore, last time it took 10 minutes before I could download the signed version.

Outrageous, 10 whole minutes? ;-)

**Comment by joker327** [comment]
> btw does auto-update of the extension work for you on mobile (firefox on android)?

Sure, considering the 24-hour update-interval (which you can edit).
