### ISSUE TITLE
New site request: [ilfattoquotidiano.it & corriere.it]

### ISSUE THREAD

**Issue by borderline23** [iamadamdev/bypass-paywalls-firefox#481]
is possible to add this sites?.
thanks for your great work

**Comment by joker327** [comment]
Paywall on ilFatto though?

**Comment by iamadamdev** [comment]
I'm not seeing any paywall on corriere.it

**Comment by london617** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-firefox-clean
