### ISSUE TITLE
extension does't work for https://www.bloombergquint.com/ 

### ISSUE THREAD

**Issue by thatmenonguy** [iamadamdev/bypass-paywalls-firefox#482]
even though the website https://www.bloombergquint.com/ is covered by the extension in the options, it doesnt seem to work on it since i am unable to view full length articles. I also tried removing cookies, blocking it etc but it simply doesnt seem to work. Could you please look into this?

**Comment by iamadamdev** [comment]
Works for me, which article are you having trouble with?
