### ISSUE TITLE
New site request: [https://www.dailytelegraph.com.au]

### ISSUE THREAD

**Issue by TesterMan247** [iamadamdev/bypass-paywalls-firefox#483]
This site can be defeated by this: ** which hasn't even been updated for a LONG time now.

Why can't your extension be updated to also work with that site?

Also, there are many other sites that work with Anti-Paywall, which your extension still cannot defeat.

How can this more than a 14 month old extension still work so well, and your continuously updated extension cannot do so well?

**Comment by joker327** [comment]
Which missing sites are still working with Nextgens though?
But indeed progress on this addon is really slow lately ...

**Comment by TesterMan247** [comment]
Well....for one: https://www.dailytelegraph.com.au

**Comment by joker327** [comment]
Obviously, but still more?

**Comment by TesterMan247** [comment]
Yeah...there's more....but I haven't tested it all yet...

**Comment by joker327** [comment]
Okay, one Australian site sofar ;-)

**Comment by iamadamdev** [comment]
Please remember I spend my free time on this and do not ask for donations or anything like that.

**Comment by joker327** [comment]
> Yeah...there's more....but I haven't tested it all yet...

You're the one named TesterMan ;-)

**Comment by TesterMan247** [comment]
> You're the one named TesterMan ;-)

Quite the funny man Mr JOKER327....

**Comment by joker327** [comment]
If you claim to bypass more sites than just deliver those sites.

**Comment by TesterMan247** [comment]
Yes, that is a fact.
However, I don't remember all those sites, and will need to test and then report back when I get some free time

**Comment by iamadamdev** [comment]
Only large or major sites will be considered. No small sites or local newspapers.
