### ISSUE TITLE
Download failure msg from Firefox

### ISSUE THREAD

**Issue by ddruck** [iamadamdev/bypass-paywalls-firefox#487]
Using the link to the latest Firefox version, there is a Firefox download failure msg identified from Github: " The file could not be downloaded because of a connection failure".

**Comment by iamadamdev** [comment]
Try https://github.com/iamadamdev/bypass-paywalls-firefox/issues/466

**Comment by ddruck** [comment]
Thanks for the response.   I did a work around by using chrome to dl the
files and then I installed the extension to firefox manually.....
