### ISSUE TITLE
New update requires permission for all website data?

### ISSUE THREAD

**Issue by jazmac** [iamadamdev/bypass-paywalls-firefox#488]
Prior to this most recent update from what I could tell, the only data needed was for permission for the relevant websites this addon deals with.

Why does it suddenly need access to all my data for web sites?

**Comment by iamadamdev** [comment]
Cause I got lazy. Every time you want to test a new site you need to add it in a billion different places. This reduces that by 1.

**Comment by mateo-36** [comment]
made an account just to +1 this issue. Asking for all web sites looks pretty gross and I will not be updating.

**Comment by jazmac** [comment]
> 
> 
> Cause I got lazy. Every time you want to test a new site you need to add it in a billion different places. This reduces that by 1.

I see. I understand it might be a hassle and this is more convenient but I feel this comes at a cost to privacy/security. So as long as this is the case I'll have to discontinue using this extension and hope you'll change your mind on this and reverse it.

**Comment by joker327** [comment]
Permissions for all sites like every other addon. You're afraid he's selling your data (no Google Analytics in addon like Chrome extension  though)?

**Comment by frm1001xplrr** [comment]
> Cause I got lazy. Every time you want to test a new site you need to add it in a billion different places. This reduces that by 1.

*feels like a coding issue, not a laziness issue

> I'll have to discontinue using this extension and hope you'll change your mind on this and reverse it.
Agreed. Hope to be back.

**Comment by banaipe95** [comment]
Dude wtf you can compile this stuff yourself. If author was willing to sell your data then he was not going to reveal the source code for that.

**Comment by noahbishop** [comment]
> made an account just to +1 this issue. Asking for all web sites looks pretty gross and I will not be updating.

Good riddance. Honestly, the amount of entitlement is uncanny! Maybe you can use your freshly created account to fork the project and make the necessary edits instead of using it to complain. The project *is* open source after all.

**Comment by TheGoddessInari** [comment]
You already update `defaultSites` in two place unnecessarily when you could include a single js to define it in both background.js and options.js.

You could always fix that (as I mentioned in the original granular permissions issue/PR) to save one place to update. Sane permissions are more important.

**Comment by Redoudou** [comment]
Hello, 
**1st  thank you @iamadamdev for this Amazing plugging and work you are doing.  This fantastic.** 

How could we help you to build this without having to give access to all our data ? What can we do to help you  ? 
@TheGoddessInari  @banaipe95  you seem to have ideas any way you could contribute and help the community ? 

Maybe we could create a bounty on Gitcoin to help solve this case ? I would rather give some money to help facilitate @iamadamdev  development.  @noahbishop What do you think ?

**Comment by TheGoddessInari** [comment]
@Redoudou I contributed the original granular permissions. Since the dev said they're lazy and @noahbishop called people "entitled", let's see how a fork goes after all.

Anything that only works on specific sites should only need permissions for those specific sites, whether webextension or userscript.

**Comment by mateo-36** [comment]
> > made an account just to +1 this issue. Asking for all web sites looks pretty gross and I will not be updating.
> 
> Good riddance. Honestly, the amount of entitlement is uncanny! Maybe you can use your freshly created account to fork the project and make the necessary edits instead of using it to complain. The project _is_ open source after all.

you sound like a dork

**Comment by joker327** [comment]
My guess is that Adam just copied it from a fork where it's actually usefull to set the all_urls-permission ;-)

**Comment by jazmac** [comment]
> 
> Good riddance. Honestly, the amount of entitlement is uncanny! Maybe you can use your freshly created account to fork the project and make the necessary edits instead of using it to complain. The project _is_ open source after all.

@noahbishop I think this just seems like a catch all way of deflecting any and all criticism of something someone has made. If we had the time/inclination to edit it ourselves then we would but that doesn't mean we can't express concerns about a product (even if it's free) or have a problem with it.

**Comment by TheGoddessInari** [comment]
It's also worth noting that the Chrome and Firefox versions can be unified (except for manifest.json; the update URL declarations mutually conflict) by swapping `browser.*` to `chrome.*` in general.

I was running on both Firefox and Chrome with one addon before deciding I didn't need the headache from trying to maintain an addon that has legal issues and couldn't simply get put in the store.

If you want to be lazy, please do it the **right** way. 🦊

**Comment by SaltyCybernaut** [comment]
> Cause I got lazy. Every time you want to test a new site you need to add it in a billion different places. This reduces that by 1.

@iamadamdev and everyone else who contributes thank you for the work you put into this extension. I no not believe anyone is try to harvest data but applying the principal to least privilege is worth the effort. We should not expect this project to be free from bugs or potential security issues and we should not expect unrealistic amounts of time being spent on security audits. So removing unnecessary permissions is a good idea.

**Comment by joker327** [comment]
> I was running on both Firefox and Chrome with one addon before deciding I didn't need the headache from trying to maintain an addon that has legal issues and couldn't simply get put in the store.

Which extension/addon though, this one?

**Comment by iamadamdev** [comment]
Thanks to @TheGoddessInari  I will be adding back the individual permissions in the next release.

**Comment by iamadamdev** [comment]
Fixed!

**Comment by texas560** [comment]
Nice, still blocking scripts for unsupported & disabled sites.
