### ISSUE TITLE
New site request: cn.ft.com

### ISSUE THREAD

**Issue by wisecrick** [iamadamdev/bypass-paywalls-firefox#490]
### New site requests - Before submitting an issue please read the following:

Only large or major sites will be considered. For small sites try the [Cookie Remover](https://addons.mozilla.org/en-US/firefox/addon/cookie-remover/) Add-on to remove cookies (might not work though).

1. Visit an article on the site you want to bypass the paywall for and copy the article title.
2. Open up a new incognito window (Ctrl+Shift+N) and paste the article title into Google.
3. Click on the same article from the Google search results page. If it loads without a paywall you can submit a request here, otherwise my extension cannot bypass it either.

Usually premium articles cannot be bypassed as they are behind a hard paywall.

**Comment by iamadamdev** [comment]
Disable uBlock Origin for that site and you should be able to read the articles. (I just loaded 10+ articles no problem even some premium ones)

**Comment by london617** [comment]
Only works for free articles (anti-adblocker script).
