### ISSUE TITLE
Permission to access data on all sites?

### ISSUE THREAD

**Issue by mk0x9** [iamadamdev/bypass-paywalls-firefox#510]
Since last update extension requests to access data on all sites. Is it intended change?

![Screenshot 2020-02-25 at 23 36 02](https://user-images.githubusercontent.com/387358/75294032-b745df80-5827-11ea-90e6-dbbd9ce03edb.png)

**Comment by trentks** [comment]
See #488 for the discussion, this is a duplicate issue.

**Comment by iamadamdev** [comment]
Fixed

**Comment by mk0x9** [comment]
Oh, sorry, thanks!
