### ISSUE TITLE
NK News no longer works ... But with an unusual block message

### ISSUE THREAD

**Issue by WanTjhenA340** [iamadamdev/bypass-paywalls-firefox#511]
So I was trying to access NKNews again after about a few days since my last access (during which your extension worked fine - I've skimmed quite a few articles of interest there). When I accessed it again earlier today though, the paywall hits back, but with a different message in which it explained that 'Your NK PRO account has expired !' or something like that (oh, and this type of account - NK PRO - is pretty much inaccessible to the general public since the only option to 'renew' it is through personal inquiries. It doesn't help either that the subscription fees are really hefty for a news site and even then, that fee only allows access to the 'regular' articles). No offers towards subscription in the article's body, just this 'account expired' message like in the screenshot.

Turning off uBlock generates the same results. Now, considering how notoriously strict this newssite's paywall is, to be honest I don't know if there's a remedy for this and should there be nothing that can be done to bypass this I'm going to just accept it, but I'd highly appreciate it if you can take a look at this. Thank you (and to the NKNews management, F*** you)
![Screenshot_20200226-172240](https://user-images.githubusercontent.com/20898244/75336428-b3649c80-58bd-11ea-86f2-aeff77f2e16a.png)

**Comment by iamadamdev** [comment]
Thanks for the heads up. Unfortunately it seems like a hard paywall now. Will be removed in the next version.
