### ISSUE TITLE
https://www.theatlantic.com stopped working weeks ago.....

### ISSUE THREAD

**Issue by Tandalai** [iamadamdev/bypass-paywalls-firefox#513]
subject line.....

**Comment by spoetnik412** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by florida922** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by iamadamdev** [comment]
Works fine with uBlock Origin also installed.
