### ISSUE TITLE
New site request: blogs.wsj.com

### ISSUE THREAD

**Issue by hub2git** [iamadamdev/bypass-paywalls-firefox#515]
The extension works well for wsj.com articles

But not for  blogs.wsj.com articles.

For example, 
https://blogs.wsj.com/experts/2020/03/06/how-productivity-apps-can-make-us-less-productive-and-less-happy/?mod=e2tw

**Comment by florida922** [comment]
Use https://github.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by hub2git** [comment]
Thanks, @florida922 . The ”clean” extension by @magnolia1234 works. Can you tell me why @iamadamdev's version doesn't work?

**Comment by florida922** [comment]
Adam didn't (yet) copy magnolia's fix, I guess ;-)
Current fix was only restricted to articles (not blogs).

**Comment by hub2git** [comment]
Are there any disadvantages to using Magnolia's version, relative to Adam's? Is Adam's version just a copycat?

**Comment by florida922** [comment]
Magnolia's repo is a progressed hard fork/mirror of Adam's repo.
With the default-release you can also add custom sites, but there's also a limited permissions release (custom sites not working then)
Btw this conversation will be deleted soon. Adam can't handle 'criticism' ;-)
