### ISSUE TITLE
The Times newspaper cannot work as of 15/03/20

### ISSUE THREAD

**Issue by xavierxu99** [iamadamdev/bypass-paywalls-firefox#519]
always asking subscribe or login or try a free trial ,cant read the full article, other ones have the same problem?

**Comment by iamadamdev** [comment]
Which article? It's working fine for me for the 5+ articles I tried.

**Comment by xavierxu99** [comment]
such as https://www.thetimes.co.uk/edition/news/coronavirus-death-toll-leaps-and-forces-boris-johnson-to-act-nhbc5ctb9 and https://www.thetimes.co.uk/edition/news/retailers-warn-against-panic-buying-during-coronavirus-crisis-gqh8230tc

cookie remover extension installed, but no effect either removed or not removed

**Comment by xavierxu99** [comment]
maybe because i connect by proxy?is that the reason?

**Comment by xavierxu99** [comment]
problem resolved! due to selection of proxy sites, some proxy site  just doesn't work, just change into another one until that it works.thank you adam！
