### ISSUE TITLE
demorgen.be no longer works

### ISSUE THREAD

**Issue by bucovaina** [iamadamdev/bypass-paywalls-firefox#524]
Hi maintainer!

Recently demorgen.be changed its paywall. Before I could still access it without the bypass-paywalls-firefox plugin by surfing in private mode and opening a new window for each article (one article for free policy). Since this week that no longer works. I also tried with a TOR browser without success. I followed the troubleshooting steps and unchecked *general paywall bypass* in the options, but that also doesn't work. 

When a page loads, I quickly see the full content, then a (paywall) banner appears so I guess it should still be possible to bypass it somehow.

**Comment by iamadamdev** [comment]
Fixed in latest version.
