### ISSUE TITLE
Causes redirect loop on MS Teams

### ISSUE THREAD

**Issue by ohthehugemanatee** [iamadamdev/bypass-paywalls-firefox#6]
This addon causes a redirect loop when logging into Microsoft Teams. Login redirects through teams.microsoft.com > login.microsoftonline.com > csp.skype.com > teams.microsoft.com. I'm not sure what information is getting lost along the way, but disabling Bypass Paywalls fixes the problem. :(

**Comment by iamadamdev** [comment]
Fixed in v1.2.4
