### ISSUE TITLE
Haaretz.co.il stoped working

### ISSUE THREAD

**Issue by denimlover** [iamadamdev/bypass-paywalls-firefox#65]
Can you please fix

**Comment by iamadamdev** [comment]
Thanks for the notification, will be removed in the next version.
(referral trick won't work anymore)

**Comment by denimlover** [comment]
:( 
But it still working in Android app

**Comment by iamadamdev** [comment]
nevermind, we got a fix for it, will be fixed in the next version

**Comment by bjesus** [comment]
I'm using 1.4.0 but it still seem to not be working unfortunately

**Comment by Paz-it** [comment]
+1 @bjesus  - 1.4.0 still not working!
Thanks!
