### ISSUE TITLE
Possibility to bypass demorgen.be

### ISSUE THREAD

**Issue by Betsy25** [iamadamdev/bypass-paywalls-firefox#72]
Hi,

This is a much read newspaper in Belgium, would it be possible to bypass demorgen.be please ?

[Demorgen: Example walled article](https://www.demorgen.be/dmselect/wie-rouwt-er-nu-om-een-huisdier-waarom-het-verlies-van-een-hond-of-kat-zo-diep-kan-snijden-b530214d/)

**Comment by iamadamdev** [comment]
Unfortunately it has a hard paywall so it won't work for that site.
