### ISSUE TITLE
Haaretz.co.il website is only partly displayed

### ISSUE THREAD

**Issue by RotterSoft** [iamadamdev/bypass-paywalls-firefox#75]
Haaretz.co.il website is only partly displayed: just the header and the first paragraph can be read.

**Comment by iamadamdev** [comment]
Which article specifically? I am able to load them fully.

**Comment by iamadamdev** [comment]
Do you want to submit a PR to fix this?

**Comment by RotterSoft** [comment]
To submit a PR?

**Comment by iamadamdev** [comment]
Will remove in next version.
