### ISSUE TITLE
Remove Cookies for WSJ

### ISSUE THREAD

**Issue by cs16lover** [iamadamdev/bypass-paywalls-firefox#76]
WSJ shows paywall after 1 article read.

Wouldn't it be nice if the extension can remove all WSJ cookies (maybe as a selectable option) ?

**Comment by iamadamdev** [comment]
Do you have uBlock Origin installed? I am not seeing any paywall.

**Comment by XmansGhost** [comment]
Delete all Cookies it should work for pretty reasonable time. I do it every time it works fine and yes ublock origin is really good. It is probably best in blocking ads with a little trouble here and there but worth it. Oh i found another error in wsj site i will report it my upcoming issues.

**Comment by iamadamdev** [comment]
Fixed in 1.4.3
