### ISSUE TITLE
Glassdoor bypass broken

### ISSUE THREAD

**Issue by XmansGhost** [iamadamdev/bypass-paywalls-firefox#78]
https://www.glassdoor.co.in/Benefits/Deloitte-India-Benefits-EI_IE2763.0,8_IL.9,14_IN115.htm

You can check the error there it asks you to login. Clearing the cookise does it only for the current page/ 1 page like with other fellow in WSJ. Maybe u really can add a automatic cookie delete feature.

**Comment by iamadamdev** [comment]
Now removing cookies for glassdoor.com in v1.4.3
