### ISSUE TITLE
Extension breaks wsj live poll and causes a internal server error

### ISSUE THREAD

**Issue by XmansGhost** [iamadamdev/bypass-paywalls-firefox#79]
https://www.wsj.com/graphics/midterm-elections-2018-results/?mod=Election2018_Banner

You can go to the site. It causes a weird 500 internal server error. disabling the extension gets far to the page but doesnt actually load anything its just few banners. Even with ublock origin disabled. 
Both of my new issues are also applicable to the chrome version of the latest 1.3.4 extension.

**Comment by iamadamdev** [comment]
Try latest version
