### ISSUE TITLE
xpi file? 

### ISSUE THREAD

**Issue by jlitz** [iamadamdev/bypass-paywalls-firefox#85]
how do I install this extention now?  cannot find xpi file per intructions given  here  https://www.ghacks.net/2015/04/19/how-to-install-firefox-add-ons-directly-on-github/

**Comment by amraks85** [comment]
download the entire bypass-paywalls-firefox from github and zip file it then rename the .zip file to .xpi
use Method 1

**Comment by andreicristianpetcu** [comment]
[Click here](https://github.com/andreicristianpetcu/bypass-paywalls-firefox/releases/download/1.4.3/bypass_paywalls-1.4.3-an+fx.xpi) and it will get installed. It's signed.

**Comment by andreicristianpetcu** [comment]
I opened an issue showing how to distribute the signed addon here https://github.com/iamadamdev/bypass-paywalls-firefox/issues/86
