### ISSUE TITLE
Please sign and upload your addon on github releases or any other site!

### ISSUE THREAD

**Issue by andreicristianpetcu** [iamadamdev/bypass-paywalls-firefox#86]
Hi!
I made a one click install version of your addon.
[Click here](https://github.com/andreicristianpetcu/bypass-paywalls-firefox/releases/download/1.4.3/bypass_paywalls-1.4.3-an+fx.xpi) and it will get installed. It's signed.

How to do it officially:

1) Change or remove the id from the manifest.json
2) ZIp the contents of the addon
3) Upload it [here](https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted)
4) Download it from addons.mozilla.org as a signed XPI
5) Upload the XPI to to your repo's [releases](https://github.com/iamadamdev/bypass-paywalls-firefox/releases) page just like I did mine
6) Link the XPI from the releases from anywhere on the web. The rules on addons.mozilla.org are stricter since Mozilla should not distribute anything they think is against the law but if you host it on Github or any other site then it should be fine for Mozilla. They will take down unlisted extensions only if they harm the user. [Here is the list of unlisted extensions](https://blocked.cdn.mozilla.net/) they took down. You should be fine as unlisted.

You can host it yourself on any site as long as you offer the correct Content-Type headers so that Firefox will install and not download the XPI file.

You can ship updates with update.json just take a look at [this example](https://github.com/andreicristianpetcu/google_translate_this/blob/master/updates.json).

You can use [web-ext sign](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign) to automate signing.

**Comment by js-d-coder** [comment]
Please put this option on readme of this repo...

**Comment by andreicristianpetcu** [comment]
it's fixed

**Comment by iamadamdev** [comment]
How do you get auto-updates to work? What I have setup doesn't seem to work. But this is just on my PC. Not sure if any others who had v1.4.5 installed got automatically updated to v1.4.6

**Comment by andreicristianpetcu** [comment]
@iamadamdev unfortunately only the 1.4.6 manifest.json has an update_url. Users of 1.4.5 are stuck to that version since it is not aware of the update system. v1.4.6 is the last manual install users need. Once they have v1.4.6, Firefox will periodically check update_url. Once you change the file to contain 1.4.7, it will auto update.

**Comment by andreicristianpetcu** [comment]
no update system https://github.com/iamadamdev/bypass-paywalls-firefox/blob/v1.4.5/manifest.json#L13

with update system https://github.com/iamadamdev/bypass-paywalls-firefox/blob/master/manifest.json#L14

**Comment by andreicristianpetcu** [comment]
once you release 1.4.7, Firefox will not immediatly update. It has a polling interval. You can force the update in about:addons in upper right wheel icon, check for updates. No clue how long the polling interval is but for debugging the first actual update, it helps in troubleshooting.

**Comment by iamadamdev** [comment]
Thanks for the debugging help. My bad, I thought I checked in the updated manifest in v1.4.5
