### ISSUE TITLE
bypassing bypass blocking

### ISSUE THREAD

**Issue by myBestSoftAndPref** [iamadamdev/bypass-paywalls-firefox#88]
As you know [Bypass paywalls with Anti-Paywall for Firefox and Chrome](https://www.ghacks.net/2017/12/11/bypass-paywalls-with-anti-paywall-for-firefox-and-chrome/)

I suggest developers use a "AdBlock subscriptions" principle. You could develop an extension that does nothing itself but blocking by a "subscription list" with rules. By default you could provide links to these "subscription" lists. And there will no any reason to blocking the extension because user will add custom subscription itself.

**UPD**
In that case you also no need to update whole extension in case when paywalls are changed. You could update list of rules only.

**UPD2**
Also you could use an "adware" principle for the `addon.mozilla.com`. Developers of such adware addons spam `addon.mozilla.com` by creating a lot of the same addons with different names. Create and add your addon with different name. Fortunately automatic addon checking system can not recognize it.
Or you could use this way for simple addon signing to place the addon on the github page and let people to install the addon in Firefox of the **release** branch.

**Comment by fortran77** [comment]
Please also see: https://github.com/iamadamdev/bypass-paywalls-chrome/issues/23.

**Comment by iamadamdev** [comment]
Any PRs are welcome.

**Comment by fortran77** [comment]
It would be nice to have a label of the type "PR-WELCOME" so would-be developers can search for it and find unfixed closed issues.
