### ISSUE TITLE
Champaign News-Gazette

### ISSUE THREAD

**Issue by kstev99** [iamadamdev/bypass-paywalls-firefox#99]
Any chance that this newspaper could be added to the list?

http://www.news-gazette.com/

I tried pasting the title into google and I can open sites that way.  After so many articles (5?) there is an overlay asking you to subscribe.  I currently block the overlay but it is a pain

**Comment by iamadamdev** [comment]
Added https://github.com/iamadamdev/bypass-paywalls-firefox/releases/download/v1.4.7/bypass_paywalls-1.4.7-an+fx.xpi
